### ISSUE TITLE
xdg-open doesn't work inside gvim

### ISSUE THREAD

**Issue by aripollak** [tpope/vim-rails#172]
I was able to reproduce my :!xdg-open problem again, but only inside gvim. It seems to work fine if I do :!xdg-open URL &, though I don't know why. This was the only thing I could find about it:
http://superuser.com/questions/386646/xdg-open-url-doesnt-open-the-website-in-my-default-browser

**Comment by aripollak** [comment]
Any reason not to just add the & to the xdg-open command? The underlying issue seems to be that gnome-open or gvfs-open, called by xdg-open, backgrounds itself but GVim closes its fake terminal before gnome-open can finish its business.

**Comment by tpope** [comment]
I'd actually like to switch to delegating to netrw and wash my hands of the matter, but in the meantime, I'd merge a pull request and see if it helps.
