### ISSUE TITLE
Conflict with Rainbow Parentheses Improved

### ISSUE THREAD

**Issue by rking** [tpope/vim-rails#187]
If you get [Rainbow Parenthesis Improved](http://www.vim.org/scripts/script.php?script_id=4176)

Then add its config line:

```
au syntax * cal rainbow#activate()
```

You'll notice that it works on most Ruby code, but not on ones where vim-rails takes over the syntax.

Now's the part where I'm not quite sure who needs to adjust. I _can_ manually `call rainbow#load()`, and it will fix the coloring, because it will rebuild the generated `lv__` syntax groups. But that code expects to be able to do that once then short-circuit it on subsequent `rainbow#activate()`s.

In `autoload/rails.vim` in `RailsBufInit()` it says:

```
let &syntax = &syntax
```

Commenting out that line causes the parens to show up correctly colorized, but of course then you lose highlighting of vim-rails' custom additions.

So, any ideas about what should be fixed? Thanks!
—☈

**Comment by mainameiz** [comment]
@rking thanks for workaround!
@tpope thanks for a great plugin!
