### ISSUE TITLE
Rview search error

### ISSUE THREAD

**Issue by kikyous** [tpope/vim-rails#250]
├── reservation_details
│   ├── _communicate_form.html.erb
│   ├── create_communicate.js.erb
│   ├── _form.html.slim
│   ├── _formsss.html.erb
│   ├── _resume_form.html.erb
├── reservations
│   ├── _communicate_form.html.erb
│   ├── confirm.html.slim
│   ├── _form.html.erb
│   ├── _invoice_form.html.slim
│   ├── invoice_form.html.slim
│   ├── _reply_form.html.slim
│   ├── _reservation_form.html.slim
│   ├── _reservation_list.html.slim
│   ├── _reservation_search_customize.html.slim
│   ├── _reservation_search.html.slim

type `:Rview re<tab><tab>`
become `:Rview reservations/`
continue type `rf<tab>`
become `:Rview reservation_details/_resume_form.html.erb`

i want to search only in reservations

**Comment by tpope** [comment]
Haven't tried on this particular problem but I'm guessing [haystack.vim](/tpope/vim-haystack) plus [projectionist.vim](/tpope/vim-projectionist) does a much better job.
