### ISSUE TITLE
:Rake and Sqlite3 binding

### ISSUE THREAD

**Issue by btagliani** [tpope/vim-rails#265]
Hi, im having an issue when running the :Rake command, using Ruby 1.9.3, chruby, sqlite3 version 3.7.12 and sqlite3 gem version 1.3.7.

This is the error:

dyld: lazy symbol binding failed: Symbol not found: _rb_intern2
  Referenced from: /Users/bruno/.gem/ruby/1.9.3/gems/sqlite3-1.3.7/lib/sqlite3/sqlite3_native.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_intern2
  Referenced from: /Users/bruno/.gem/ruby/1.9.3/gems/sqlite3-1.3.7/lib/sqlite3/sqlite3_native.bundle
  Expected in: flat namespace

I have tried to do a bundle config with several different options, but none of them solved anything. Any ideas?

Thanks

Bruno

**Comment by squanto** [comment]
Fixed it for me to :+1:
