### ISSUE TITLE
disable database.yml

### ISSUE THREAD

**Issue by bhenderson** [tpope/vim-rails#282]
hi there, 

is there a way to disable setting dbext settings from database.yml?

I'm sorry, I couldn't find any docs mentioning how to do this.

**Comment by nimaai** [comment]
So it seems to me that the feature of automatically configuring dadbod using `config/database.yml` was removed without a customization option?

**Comment by tpope** [comment]
Nothing has been removed. It should still work.

**Comment by nimaai** [comment]
For me it doesn't. Simple repo to reproduce: https://github.com/nimaai/rails-dadbod-issue
1. install sqlite
2. install https://github.com/junegunn/vim-plug
3. start neovim with `nvim -u init.vim`
4. `:PlugInstall`
5. `:q`
6. start neovim with `nvim -u init.vim`
7. `:DB rails:#development`
8. error: `DB: No Rails database for environment development`

I am getting the same error with a real-world app using postgres.

**Comment by tpope** [comment]
That repo works for me. The error message is a catch-all. You might get a better one if you do `:echo rails#parse_yaml_file('config/database.yml')`.

**Comment by nimaai** [comment]
`E117: Unknown function: rails#parse_yaml_file`

**Comment by tpope** [comment]
I meant to say `rails#app().parse_yaml_file('config/database.yml')`.

**Comment by nimaai** [comment]
`E716: Key not present in Dictionary: "parse_yaml_file('config/database.yml')"`

**Comment by tpope** [comment]
🤦 `rails#yaml_parse_file('config/database.yml')`

**Comment by nimaai** [comment]
```
Error detected while processing function rails#yaml_parse_file[17]..function rails#yaml_parse_file:
line   17:
E605: Exception not caught: invalid YAML file: config/database.yml
```
this is line 17:
`<<: *default`

**Comment by tpope** [comment]
Line 17 is a source code reference, it does not identify a line in the YAML file. You can try using Ruby's `YAML.load` to learn more.
