### ISSUE TITLE
cannot load such file --      bundler/setup (LoadError)

### ISSUE THREAD

**Issue by rafaeljesus** [tpope/vim-rails#288]
After updating my Mac to Mavericks i have this when I run .Rake or Rake on my test file:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb|45| in `require': cannot load such file --      bundler/setup (LoadError)                                                                                                                                
 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb|45| in`require'
   config/boot.rb|4| in `<top (required)>'
   bin/rake|2| in`require_relative'
   bin/rake|2| in `<main>'

But in my terminal it works great,

Any ideia?

**Comment by mjacobus** [comment]
Same thing here. But commenting /etc/zshenv  did not make it.

**Comment by tpope** [comment]
FYI El Capitan itself renames `zshenv` to `zprofile`. So hopefully this problem is on its way out for good.
