### ISSUE TITLE
Spring and :Rake and Binstubs integration

### ISSUE THREAD

**Issue by patrickdavey** [tpope/vim-rails#316]
Hi,

Love vim-rails, I've been using it for quite a while and really like being able to run the tests for a specific file / just an individual test from within vim.   I've also just started to use Spring and I've run into an issue - partly looked at in #253 but I'm still getting slow tests.

In my particular app I'm using sunspot which _may_ have something to do with why I'm having slower tests.

Anyway.. if I run from the command line:
`time bin/rspec spec/helpers/contests_helper_spec.rb`

It uses Spring and comes out at _3.047 seconds_.

If I open up the same helper in Vim and run .Rake (just the one test in there at the moment) it runs the following command which I time here:

`time bin/rake spec SPEC=spec/helpers/contests_helper_spec.rb`

come out as _12.162 seconds_

obviously one is using /bin/rake and the other is just me using /bin/rspec .  Can you give any pointers as to where I can go to fix this?  The answer may be "it's just the way your app is structured, sorry!"  but I thought I'd ask.

Thanks,
Patrick

**Comment by waiting-for-dev** [comment]
`Rrunner` is still slower than ` Rake`. Using [a function to measure command execution time in vim](http://vim.wikia.com/wiki/Measure_time_taken_to_execute_a_command), for an integration test I have out there, I get `7` with `Rrunner` and `9` with `Rake`. On the other hand, `Rake` output looks much nicer than `Rrunner` one. For example:

With `Rrunner`:

    || Run options: include {:locations=>{"./spec/models/accountancy/account_spec.rb"=>[61]}}
    || F
    || 
    || Failures:
    || 
    spec/models/accountancy/account_spec.rb|61 error|  Failure/Error: expect(account.errors.added?(:code, :account_has_not_lower_levels)).to eq(true) expected: true got: false (compared using ==)
    || 
    || Finished in 0.14439 seconds (files took 2.56 seconds to load)
    || 1 example, 1 failure
    || 
    || Failed examples:
    || 
    || rspec ./spec/models/accountancy/account_spec.rb:53 # Accountancy::Account lower levels validation doesn't add an error if there is an account for each lower level and the same owner

With `Rake`:

    || Run options: include {:locations=>{"./spec/models/accountancy/account_spec.rb"=>[61]}}
    || F
    || 
    || Failures:
    || 
    ||   1) Accountancy::Account lower levels validation doesn't add an error if there is an account for each lower level and the same owner
    ||      Failure/Error: expect(account.errors.added?(:code, :account_has_not_lower_levels)).to eq(true)
    ||        
    ||        expected: true
    ||             got: false
    ||        
    ||        (compared using ==)
    spec/models/accountancy/account_spec.rb|61| in `block (3 levels) in <top (required)>'
    || 
    || Finished in 0.13594 seconds (files took 2.75 seconds to load)
    || 1 example, 1 failure
    || 
    || Failed examples:
    || 
    || rspec ./spec/models/accountancy/account_spec.rb:53 # Accountancy::Account lower levels validation doesn't add an error if there is an account for each lower level and the same owner

It would be great to have readability and speed on the same side :)

**Comment by tpope** [comment]
`:Rrunner`'s output is *way* more helpful in terms of what is echoed with commands like `:cc`, FWIW.

**Comment by waiting-for-dev** [comment]
This is true. But I would prefer to have the nice looking view in `:copen`, because following is what I usually do:

1. I run the test.
2. Quickfix window is opened automatically ("`:copen` view") where I see the error.
3. I close quickfix window and solve the error.

I understand that other people can prefer the other way. But I don't understand why it is different in `Rrunner` and `Rake`. What's the point? Ideally you should be able to configure which view you want to get. Now ,at least when running tests, you have to choose between nice looking (in my `:copen` prefference) or speed, which shouldn't be mixed things.

**Comment by tpope** [comment]
You can achieve the execution you want with `:Dispatch -compiler=rails bin/rspec ...`. The latest commit makes it possible to set it as the `:Dispatch` default using a `"dispatch"` projection. That's about as far as I'm willing to go.

**Comment by waiting-for-dev** [comment]
Ok, thanks. I'll look further into this commit.

**Comment by eremite** [comment]
Does this make it possible for me to use my own rake wrapper? I tried:

```vim
let g:rails_projections = {
\   "*": {
\     "dispatch": "/my/custom/rake"
\   }
\ }
```

But it didn't work, so I must be misunderstanding something. Or maybe there's already a better way to do this? (Currently I `return '/my/custom/rake'` at the start of `function! s:app_rake_command`.)

**Comment by tpope** [comment]
No, it let's you control what happens when you call `:Dispatch<CR>`.

Projectionist lets you set a `"make"` projection key and I think porting something similar to rails.vim would be the way to go. Though rake looks like it might be going away in Rails 5 so none too eager to dig in. (Also, can't you just make a custom binstub?)

**Comment by eremite** [comment]
Ah, OK, that makes sense. What I'm actually doing is running the command in a docker container (`docker-compose run --rm web bundle exec rake`) so committing that to `bin/rake` would break the production app. But that's probably not a common enough use case to bother about, so I'm fine with my current workaround.

P.S. Thanks for taking the time to respond. I really appreciate all your awesome plugins!

**Comment by mecampbellsoup** [comment]
@tpope Hello Tim! Quick Q, now that Rails' spring preloader has improved to the point of being usable (IMHO), is there any specific step(s) to make sure a `dispatch`'ed `rspec` command is passed to my spring server? Currently I just have this line in my `.vimrc`:

```vim
let g:rspec_command = "Dispatch rspec {spec}"
```

Thanks!

**Comment by tpope** [comment]
It should work transparently so long as `bin/rspec` uses spring.

**Comment by mecampbellsoup** [comment]
I ended up adding [`spring rspec` bitstub](https://github.com/jonleighton/spring-commands-rspec) switching my command to:

```vim
let g:rspec_command = "Dispatch bin/rspec {spec}"
```

**Comment by tpope** [comment]
FYI `g:rspec_command` isn't a rails.vim option. That must be for some other plugin.
