### ISSUE TITLE
Configurable quote style for Rextract's `render 'foo'`

### ISSUE THREAD

**Issue by henrik** [tpope/vim-rails#343]
Would you accept a patch for (or add yourself) a way to configure the quote style used for `Rextract`'s `render 'foo'` string? Our team has a double-quote convention so being able to configure that would remove a tiny annoyance.

**Comment by tpope** [comment]
Let's just change it and see who complains.

**Comment by henrik** [comment]
:thumbsup: Thanks for that!

**Comment by jeromedalbert** [comment]
> Let's just change it and see who complains.

I do. 😁 Our team has a single-quote convention. I guess the best solution is to have a vim-rails global option?

**Comment by henrik** [comment]
@jeromedalbert Clearly the best solution is for your team to see the light ;D Kidding.

**Comment by jeromedalbert** [comment]
@henrik made a quick PR, for what it's worth!
