### ISSUE TITLE
Efabricate 

### ISSUE THREAD

**Issue by andy4thehuynh** [tpope/vim-rails#359]
I love the [Fabrication gem](https://github.com/paulelliott/fabrication). I dig `:Efixtures` but find myself wanting a `:Efabricator` command to access my fabricators in `spec/fabricators/`.

Is there a want or need for this? Just an idea Tim ;)

**Comment by joallard** [comment]
@tpope Would you be open to a Wiki page eg. "Projection recipes" for people to share them without necessarily polluting the codebase?

**Comment by tpope** [comment]
That sounds like a good idea.

**Comment by joallard** [comment]
Coolbeans. The wiki looks disabled for now, but I'd have no problem creating the page and adding the recipes I have. The other part would just be adding a link on the Readme and we'd be all set!

**Comment by tpope** [comment]
Enabled

**Comment by joallard** [comment]
@tpope We have a [stub](https://github.com/tpope/vim-rails/wiki/Projection-Recipes)!
