### ISSUE TITLE
Warning when run :Rake

### ISSUE THREAD

**Issue by betoharres** [tpope/vim-rails#374]
Although it runs my tests correctly, I get this warning before the test result every time I run saying: 

*Warning: You're using Rubygems 2.0.14 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.*

Which isn't correct, I updated few months ago to ruby version 2.1.3.

Any hints?

**Comment by tpope** [comment]
You can check if `:echo $PATH` (Vim's path) and `:!echo $PATH` (the shell's path) are as you expect.

You might also try the latest, as there's been some tweaking of binstub handling.

**Comment by betoharres** [comment]
I end up reinstalling my OS, everything works finde now. This can be closed :) Thanks!

**Comment by Illbay** [comment]
I'm not sure that "reinstalling my OS" is the proper solution to the problem such that it can be closed.

**Comment by tpope** [comment]
Of course not, but whatever it is is definitely a machine setup issue, not a rails.vim issue, as evidenced by `:!bin/rake` failing.
