### ISSUE TITLE
Filename mismatching the real one

### ISSUE THREAD

**Issue by Davidslv** [tpope/vim-rails#376]
Hello,

Is it possible when using `:Rcontroller`, `:Rmodel` (etc..) to open the file with the right name?
For example sometimes I type the name of the model with a capital letter and then Vim opens it with a capital letter, this already caused me problems with the filename not matching the real one and I have to close Vim to go back to normal. I'm attaching some screenshot hoping it makes it easy my explanation.

Thank you for your time writing this plugin.

![screen shot 2014-12-17 at 11 10 01](https://cloud.githubusercontent.com/assets/136777/5470265/b97d1dd0-85dd-11e4-8303-913496290693.png)
![screen shot 2014-12-17 at 11 10 14](https://cloud.githubusercontent.com/assets/136777/5470266/b9814eb4-85dd-11e4-9847-e977233bfd68.png)
![screen shot 2014-12-17 at 11 11 54](https://cloud.githubusercontent.com/assets/136777/5470264/b97cdd16-85dd-11e4-9e85-e45dc63c1f5e.png)

**Comment by tpope** [comment]
Sounds related to case insensitive file systems, but I can't reproduce. `:Emodel User` produces "No such model User". Do you get the same problem if you do `:e app/models/Promocode.rb`?

**Comment by Davidslv** [comment]
Hello @tpope I use `OSX 10.10.1 (Yosemite)` but happens the same on the previous versions

I don't get that error message, it actually opens the file, but recognises it with a capital letter or any other case insensitive combination.

I think I also forgot to add more information, for example in this case I was trying to do `:Gblame`
![screen shot 2015-01-20 at 10 05 19](https://cloud.githubusercontent.com/assets/136777/5815278/26182ebc-a08c-11e4-9480-cd72ce0a4762.png)

Which clearly failed to find the correct file. I hope I have provided a better description now.

Thank you once again.
David

**Comment by tpope** [comment]
You didn't answer "Do you get the same problem if you do `:e app/models/Promocode.rb`?"

**Comment by Davidslv** [comment]
Sorry, I though I did. So If I do `:e app/models/Promocode.rb` it opens the file with a capitalise `P`, which is basically the same problem.

**Comment by tpope** [comment]
Yeah that's correctly lowercased for me in MacVim. I can reproduce the problem in the built-in OS X Vim. I'd say that's the real problem, and it has nothing to do with rails.vim.

**Comment by Davidslv** [comment]
I see, I actually use the built-in OS X Vim... oh well...

Thank you for having a look
