### ISSUE TITLE
:Rake - make: Nothing to be done for `spec'

### ISSUE THREAD

**Issue by brunomeira** [tpope/vim-rails#380]
Everytime I try to run :Rake on my rspec test it gives me a message "make: Nothing to be done for `spec'" and the test is not executed

**Comment by tpope** [comment]
Does `rake spec` work?

**Comment by brunomeira** [comment]
yes, it works fine

**Comment by tpope** [comment]
What's the output of `:verbose set makeprg?`.

**Comment by brunomeira** [comment]
makeprg=make

**Comment by tpope** [comment]
How about `:echo rails#app().rake_command()`?

**Comment by brunomeira** [comment]
bin/rake

**Comment by tpope** [comment]
Do you have dispatch.vim? Whatever your answer, can you try the opposite?

**Comment by brunomeira** [comment]
I didn't have it. But just installed and now both "Rake" and "Dispatch" are working. Thanks!

**Comment by tpope** [comment]
Let the record show it should function without dispatch.vim as well. Seemingly makeprg is incorrect for you in that case.
