### ISSUE TITLE
Sass syntax breaks after @media declarations

### ISSUE THREAD

**Issue by Bastes** [tpope/vim-rails#381]
With @media declarations:
![with-media](https://cloud.githubusercontent.com/assets/10667/5754755/53feacae-9c9d-11e4-985e-a02972c757f0.png)

Without:
![without-media](https://cloud.githubusercontent.com/assets/10667/5754756/56c90650-9c9d-11e4-85a9-5241b6284292.png)

I'm not too versed in vim syntax programming (or I'd already be trying to submit a fix), hope this helps pinpoint the problem.

Keep on the good work, vim-rails is awesome ^^d

**Comment by tpope** [comment]
This is an issue with your Sass highlighting ([from vim-haml?](/tpope/vim-haml)), not vim-rails.

**Comment by Bastes** [comment]
Thanks for pointing me in the right direction, and sorry for the noise ^^d
