### ISSUE TITLE
can't find "contact.rb" in path

### ISSUE THREAD

**Issue by githorse** [tpope/vim-rails#383]
I have some related models, mostly superclasses and subclasses, grouped inside folders in my app/models directory (e.g., the folder 'contacts' contains `contact.rb`, `user_contact.rb`, `email_contact.rb`, etc.). This works because I have the line 

    config.autoload_paths += Dir["#{config.root}/app/models/**/"]

in my `config/application.rb`. However, vim-rails doesn't seem to find these files via the `gf` command -- I get the error above. (`gf` works fine on files actually inside the app/models directory.) Is there a workaround for this?

**Comment by tpope** [comment]
You can fiddle with the `'path'` option.  But before you bother, maybe consider not completely breaking nested modules for something so unnecessary?

**Comment by githorse** [comment]
Touché. But hey, OCD is a diagnosable disorder :)

On Thu, Jan 29, 2015 at 11:41 AM, Tim Pope <notifications@github.com> wrote:

> You can fiddle with the 'path' option. But before you bother, maybe
> consider not completely breaking nested modules for something so
> unnecessary?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tpope/vim-rails/issues/383#issuecomment-72057791>.
>



-- 
<https://www.google.com/search?tbm=isch&hl=en&source=hp&biw=1436&bih=806&q=columbia+engineering#hl=en&tbm=isch&q=large+hadron+collider&spell=1&sa=X&ei=G8tNUcnrB-Hg0gGut4H4Ag&ved=0CE8QvwUoAA&bav=on.2,or.r_cp.r_qf.&bvm=bv.44158598,d.dmQ&fp=d9f5d979378254d8&biw=1436&bih=762>
Ryan Corbett Turner
M.S., Computer Science, 2012
rct@caa.columbia.edu <rct@caa.olumbia.edu%3Cemail>
