### ISSUE TITLE
Error detected while processing function rails#buffer_setup

### ISSUE THREAD

**Issue by mmikitka** [tpope/vim-rails#384]
Last week, I upgraded all my bundles, including vim-rails, and I now see the following error message whenever I invoke a :Gdiff against a file, using tpope/fugitive.

Error detected while processing function rails#buffer_setup..<SNR>220_readable_calculate_file_type..<SNR>220_buffer_name:                                                       
line    8:
E716: Key not present in Dictionary: path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function tolower(app.path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function s:startswith(tolower(f),s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""
E15: Invalid expression: s:startswith(tolower(f),s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""

If relevant, I use the [spf13-vim](/spf13/spf13-vim) Vim framework

**Comment by dalizard** [comment]
I am experiencing the same problem. I am running OS X 10.10.2, and latest version of `vim-rails`, and `vim-fugitive`. The problem happens, when I do `:Gblame` and `Enter` on any of the lines. Vim is installed via homebrew:

```bash
~/P/Rails (master|✔) $ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  6 2014 14:32:04)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```
Error message is:

```
Error detected while processing function rails#buffer_setup..<SNR>42_readable_calculate_file_type..<SNR>42_buffer_name:
line    8:
E716: Key not present in Dictionary: path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function tolower(app.path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function s:startswith(tolower(f),s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""
E15: Invalid expression: s:startswith(tolower(f),s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""
Press ENTER or type command to continue
```

**Comment by tpope** [comment]
I can't reproduce. e13ee81882c2e4c1bba022914a04e3f7cd6fc5d6 is almost certainly the culprit. The old behavior was dumb so I don't want to revert.

Can you check `:echo b:rails_root` and see what it reports?

**Comment by dalizard** [comment]
```
:echo b:rails_root
E121: Undefined variable: b:rails_root
E15: Invalid expression: b:rails_root
Press ENTER or type command to continue
```

**Comment by tpope** [comment]
I meant to specify, that's in the fugitive buffer, correct?

**Comment by dalizard** [comment]
Yes, in the `fugitive` buffer.

**Comment by tpope** [comment]
So here's the confusing part: `rails#buffer_setup()` short circuits if there's no `b:rails_root`.

```
function! rails#buffer_setup() abort
  if !exists('b:rails_root')
    return ''
  endif
  let self = rails#buffer()
  let b:rails_cached_file_type = self.calculate_file_type()
```

Maybe it's getting unset? You can throw an `:echomsg b:rails_root` after `endif` to see.

**Comment by dalizard** [comment]
It is set properly, it seems. It returns:
```
fugitive:///Users/Sleepwalker/Projects/Rails/.git
```
which is correct. The changed code looks like:
``` vim
function! rails#buffer_setup() abort
  if !exists('b:rails_root')
    return ''
  endif
  echomsg b:rails_root                                                                                                                                                                                      
  let self = rails#buffer()
  let b:rails_cached_file_type = self.calculate_file_type()
```

**Comment by tpope** [comment]
That explains it. The commit I mentioned is stricter about rejecting it, but even before that, rails.vim would have been largely broken. I'm guessing something in your config is setting it?

**Comment by dalizard** [comment]
I started from scratch (`vim -u NONE -N`) and only added `vim-rails` and `vim-fugitive` - problem was still present. I started vim in the way I use it (all plugins loaded + vimrc), and only removed `vim-rails` - problem was gone. I did `git bisect` on `vim-rails` and the problem came from the exact same commit you mentioned - e13ee81. Any further suggestions?

**Comment by tpope** [comment]
I guess try checking `RailsDetect()` both interactively and with the same function edit and see if it returns 1 or 0.

**Comment by dalizard** [comment]
The problem is that it always returns 1, because `b:rails_root` exists even on non-Rails projects.

**Comment by tpope** [comment]
Oh, catch 22. You might gut that part so the `findfile` path gets exercised.

**Comment by dalizard** [comment]
Okay, I might need a bit more guidance here, since I've never written in vimscript :) The problem (as far as I see it) is that

```
 let file = findfile('config/environment.rb', escape(fn, ', ').';')
  if !empty(file)
    let b:rails_root = fnamemodify(file, ':p:h:h')
    return 1
  endif
```

the `file` is never empty, and the `if` statement is always executed. I used `filereadable` and that seemed to work from what I saw, but I might be breaking something else, or doing it wrong.

**Comment by tpope** [comment]
File should be the location of `config/environment.rb`. If it doesn't exist, it should be blank. What is it in the broken case?

**Comment by dalizard** [comment]
It's not blank, it's always present. I mean, it always returns a path, which is invalid:
```
let file = findfile('config/environment.rb', escape(fn, ', ').';')
echomsg file
```
```
~/.dotfiles (master|✚1) $ pwd
/Users/Sleepwalker/.dotfiles
```

And the result is `fugitive:///Users/Sleepwalker/.dotfiles/.git/config/environment.rb`

**Comment by dalizard** [comment]
Why is it prepending the path with `fugitive://`? That seems to be breaking the `findfile()` or I am wrong?

**Comment by tpope** [comment]
It's using the buffer path. I would expect it to break `findfile()`, meaning it would return an empty string. What is `fn`?

**Comment by dalizard** [comment]
`fn` is always including a git hash:
```
fugitive:///Users/Sleepwalker/.dotfiles/.git//22d734bedac7aa8137111bc7a6fa08da30d6f46e
```
or
```
fugitive:///Users/Sleepwalker/Projects/XORCipher/.git//a361fe17b85544f9c73e5f7a218b02eaf5e7ae5e
```

**Comment by dalizard** [comment]
`findfile()` seems to be breaking (working as expected) when the `fugitive://` buffer path is not present

**Comment by tpope** [comment]
That's what I would expect. With the appropriate commit open, try

    echo findfile('config/environment.rb', 'fugitive:///Users/Sleepwalker/.dotfiles/.git//22d734bedac7aa8137111bc7a6fa08da30d6f46e;')

When I do the equivalent, I get nothing. I take it you don't?

**Comment by tpope** [comment]
Actually since you reported the value before the `fnamemodify(fn, ':h')`, you probably want tot try:

    echo findfile('config/environment.rb', 'fugitive:///Users/Sleepwalker/.dotfiles/.git;')

**Comment by dalizard** [comment]
I get this
```
fugitive:///Users/Sleepwalker/.dotfiles/.git/config/environment.rb
```

And for sake of clarity, here's the complete function
```
function! RailsDetect(...) abort
  if exists('b:rails_roots')
    return 1
  endif
  let fn = fnamemodify(a:0 ? a:1 : expand('%'), ':p')
  if !isdirectory(fn)
    let fn = fnamemodify(fn, ':h')
  endif
  echo findfile('config/environment.rb', 'fugitive:///Users/Sleepwalker/.dotfiles/.git;')
  let file = findfile('config/environment.rb', escape(fn, ', ').';')
  if !empty(file)
    let b:rails_root = fnamemodify(file, ':p:h:h')
    return 1
  endif
endfunction
```

**Comment by tpope** [comment]
I see now you're using the OS X default Vim. More proof that it's unusably broken. Pushed a workaround.

**Comment by dalizard** [comment]
Ahg! Good catch! I was using neovim for a while, but it segfaulted with vim-dispatch, so I went back to vim. However, I must have wiped the vim installed via Homebrew, and wasn't actually aware of the fact that I was using OS X default vim. I have no problem with Homebrew vim. Certainly system vim is broken. But now you've fixed it accidentally :) Thank you!
