### ISSUE TITLE
Overriding native `gf`

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-rails#385]
Is there a specific reason why you've ended up overriding `gf`? Setting `path` should ideally be good enough and vim will take care of the rest.

The reason this is a problem is because your custom `gf` does not conform to using `suffixesadd` like the native one and hence is predisposed to look only for ruby files. The overriding may also be breaking other important vim configurations such as `suffixes`, `includeexpr`, `isfname` etc though I haven't exhaustively tested all of these.

However I feel this is very bad for obvious reasons because although `ruby` files are most likely the most important ones, I don't think they are ever going to be the `only` files that matter, there are loads of other files (mostly assets) of various different filetypes and that can change with time as newer technologies come and replace existing ones too.

I understand that vim-rails may not choose to care about files other than `ruby` ones and I would still find it sort of acceptable (though not very cool), but it would make sense to forward the lookup request ahead to native `gf` when your custom `gf` function fails to find a file (in worst case, native `gf`should still be better IMO, correct me if I am wrong).

Let me know what you think.

PS: I am sorry if this has been discussed previously, I tried looking for a similar conversation but didn't find any so decided to open a new issue for it.

**Comment by tpope** [comment]
There are dozens of special cases that would be impossible without remapping. Pressing `gf` on `has_many :posts` takes you to `app/models/post.rb`. It's mostly Ruby but there is some support for asset file types too. What is your actual problem?

**Comment by dhruvasagar** [comment]
That sounds fair. My actual problem is within javascript files when I do a 'gf' it looked for a '.rb' file, I think this happens when I do a gf on something like 'TheApp', it looks for 'the_app.rb' and not 'the_app.js'

**Comment by tpope** [comment]
So yeah, that could definitely be changed. I suspect this will uncover other problems (`::` vs `.`, wrong `'path'`, etc.).

**Comment by phanhaiquang** [comment]
I have similar issue and vim-node (https://github.com/moll/vim-node) resolved my issue.

**Comment by tpope** [comment]
As it happens, [a recent change](https://github.com/tpope/vim-rails/commit/3de4e4f5aa672e78e1cf41b4de85bccad296a74d) gave `gf` precedence to other plugins for non-Ruby filetypes. Glad to see it's working.
