### ISSUE TITLE
Option to not load Rails.vim

### ISSUE THREAD

**Issue by avdgaag** [tpope/vim-rails#391]
Rails.vim is awesome, but it is currently activated for any project with a `config/environment.rb`. A [Lotus](http://lotusrb.org) project also has a `config/environment.rb`, so rails.vim will activate for it — but being a different framework most functionality mostly doesn't work or simply doesn't make sense. Rake.vim is great, but if I want to make a custom Vim plugin for working with Lotus projects and their conventions, I would need a way to not activate Rails.vim at all (and preferably keep Rake.vim).

Here's some strategies I can think of:

1. Change the detection of Rails apps to something more sophisticated, such as detecting `gem "rails"` in `./Gemfile`.
2. Adding a global Vim configuration you can put in your `~/.vimrc` to skip loading Rails.vim for certain paths.
3. Adding a `do_not_load_rails_vim` setting in a project-specific `vimrc` file.
4. Uninstall Rails.vim altogether and re-install when switching to a Rails project where you _do_ need it.

To me these all sound equally bad. Is there any way to accomplish this, that I am unaware of? Any thoughts on the matter?

**Comment by tpope** [comment]
I think I would be okay with an additional static check (i.e., no Gemfile parsing malarky). Perhaps the presence of an `app/` directory?

**Comment by avdgaag** [comment]
An `app/` directory would certainly fix my particular use case (since Lotus uses an `apps/` directory instead), but I feel like it may only be a minor improvement over detecting `config/environment.rb`. I can imagine a Sinatra application having the latter but not the former, so this wouldn't help there — but that's mere conjecture, and I cannot think of a better test. So let's go for it.

Do you want me to take a stab at implementing this, or would it be quicker to do it yourself?

**Comment by avdgaag** [comment]
Awesome, thanks.
