### ISSUE TITLE
Feature request: AS!

### ISSUE THREAD

**Issue by vicramon** [tpope/vim-rails#392]
I'd love to be able to create a spec file automatically with AS! . I do it all the time, it'd save me a lot of typing. What do you think?

**Comment by klebershimabuku** [comment]
I would love to have such feature but I was wondering about the same :A that we are already usually to open the respective spec file, could ask us for create if the file doesn't exist.

**Comment by tpope** [comment]
I discussed my concerns with this in #135. I am increasingly warming up to the idea of "prompt to create", though, and might experiment with that after cutting a release in the next week or two. You are welcome to start prototyping it.

**Comment by tpope** [comment]
I should add that I am thinking of using `inputlist()`, solving the "which file" problem as well.
