### ISSUE TITLE
:Estylesheet – do not add file extensions if provided

### ISSUE THREAD

**Issue by firedev** [tpope/vim-rails#393]
Rails 4 is dropping `.css` and I am using `.sass` so I think it would be best to allow users to be able to specify their extensions as it is the case with `:Eview`

Given:
`:Estylesheet _history.sass!`

Expected:
`/app/assets/stylesheets/_history.sass`

Actual file created:
`/app/assets/stylesheets/_history.sass.css.scss`

**Comment by tpope** [comment]
Fixing this to respect the given file extension is harder but dropping the `.css` is super easy. Change your  `config.sass.preferred_syntax` in `config/application.rb` if you want to force `sass` over `scss`.

**Comment by firedev** [comment]
With all respect, is it possible to actually make it work the same way `:Eview` does? I.e. to use filename provided if there is an extension specified?

**Comment by tpope** [comment]
Possible, yes, and that would be the ideal behavior. I won't be getting to it in the near future but you are welcome to take a stab at it.
