### ISSUE TITLE
`gf` only looking for .rb files

### ISSUE THREAD

**Issue by jasonlong** [tpope/vim-rails#396]
This used to work fine for me, so I'm guessing I have some sort of configuration problem and I can't seem to figure it out.

Is there something that would cause `gf` to only look for `.rb` files?

For example, hitting `gf` in this scenario (where * is the cursor position):

```
<%= render :partial =>  "shared/hea*der" %>
```

gives an error message of `E447: Can't find file "shared/header.rb" in path`.

Similarly, `gf` here:

```
has_many :us*ers
```

gives an error message of `E447: Can't find file "user.rb" in path`.

FWIW I'm using [vim-plug](https://github.com/junegunn/vim-plug) for my plugin manager.

**Comment by tpope** [comment]
This sounds like the `gf` map might be missing. Do you see it with `:nmap gf`?

**Comment by jasonlong** [comment]
Thanks for the quick reply @tpope. This is what I see w/ `:nmap gf`:

```
*@:<C-U>exe <SNR>105_gf(v:count1,"gf",'edit')<CR>
```

Is that correct?

**Comment by tpope** [comment]
That's the `gf` map from vim-ruby, not rails.vim. Are you sure the plugin is activated? Can you call `:Emodel`?

**Comment by jasonlong** [comment]
Looks like you're right in that the plugin isn't activated. `:Emodel` doesn't work even though vim-plug says that it has loaded vim-rails. 

I'll continue to investigate, but feel free to close this since it doesn't seem to be a problem with the plugin.

**Comment by tpope** [comment]
The plugin may be loaded but it needs to recognize your Rails app to activate. Generally, this requires `config/environment.rb` and `app/` to exist.

**Comment by jasonlong** [comment]
Yep, definitely have those directories. Is there a way of checking that the plugin is loaded even though it might not be active?

**Comment by tpope** [comment]
If you see `plugin/rails.vim` in `:scriptnames`, it's loaded. If you also see `autoload/rails.vim`, that suggests it was activated at some point.

**Comment by jasonlong** [comment]
Ok, I do see it in `:scriptnames`, but I don't see it under `autoload`. 

When working on my app, I checked that `:pwd` says the root Rails app directory. Does that indicate where the plugin would be looking for `app/` and/or `config/environment.rb`?

**Comment by tpope** [comment]
`:pwd` is irrelevant; it's based on the directory hierarchy of the current file. Convoluted symlinks can confuse it, for example.

You should also check one commit back, as this was very recently tweaked.

**Comment by jasonlong** [comment]
I see that change your talking about @tpope. I did some clumsy debugging and found that the code in the conditional at https://github.com/tpope/vim-rails/blob/c7aeb5b8923e744b8fb753ddf881185abc16eef9/plugin/rails.vim#L37 never gets executed, even when killing the second part of the `if`.

I might be losing my mind, but I feel like `findfile()` isn't working as expected for me. I opened a controller and tried `:echo findfile("Gemfile", ".;")` since there is a `Gemfile` in the root directory and this returned false.

I need to run for now, but I'll keep poking at it. Thanks for all your help. :bow:

**Comment by jasonlong** [comment]
Wow, you'll never believe this. After a *lot* of off and on debugging, I finally figured out why this isn't working.

I had this line in my `.vimrc`:

```
set wildignore+=*.DS_Store,*~,,.git\*,.svn\*,*.swp,*.tmp,*.zip
```

Note the extra comma before the `.git`. Removing one of those commas made everything work normally. Crazy.

Sorry for the false alarm. :grimacing:
