### ISSUE TITLE
:Rake on test file with binding.pry debug can not work in Neovim

### ISSUE THREAD

**Issue by lingceng** [tpope/vim-rails#397]
I use neovim.
And I use gem 'pry-byebug', "~> 2.0.0" to debug.

When I run :Rake on test code like following

    test 'something'
      binding.pry
      assert true
    end

The interactive debug console will not work.

I find some similar issue here: https://github.com/tpope/vim-fugitive/pull/624
Maybe it's a problem of neovim. 

I try to fix the problem by using `tabnew | terminal` instead of bang command. But failed.
I seems more complicated when call :Rake on a test. Because it calls :make command. 

I wish someone can help.

**Comment by tpope** [comment]
`:make` captures output with `2>&1 | tee` which can interfere with some interactive tools. Not really much I can do about it, I'm afraid. You can try with dispatch.vim, which has some alternate ways of running things (e.g., tmux).

**Comment by ashwinvidiyala** [comment]
Did anyone find a solution to this? For the longest time I was able to access the `pry` console while running tests using `:TestNearest`, but it hasn't been working of late.

**Comment by tpope** [comment]
With dispatch.vim and vim-dispatch-neovim, you can use `:0Spawn` to run the current file's test in a terminal, or `:.Spawn` to run the test under the cursor.

**Comment by ashwinvidiyala** [comment]
Thanks for that @tpope , but that's not the issue. I am able to run tests using `:TestNearest` and the other `vim-test` commands. My issue is that if I throw in a `binding.pry` in the test, I don't see the `pry` console open up anymore in the test window. That used to work before, and I can't figure out why.

**Comment by tpope** [comment]
This isn't `vim-test`.

**Comment by ashwinvidiyala** [comment]
> This isn't `vim-test`.

Shit. You're right. My bad dude. Thanks!
