### ISSUE TITLE
gf + <C-o> error

### ISSUE THREAD

**Issue by eugen0329** [tpope/vim-rails#406]
Hi, Tim! The feature gf do not work after I pressing \<C-o\> to return to previous buffer.
How to reproduce:
1) Type gf, when cursor under the proper location, where the plugin performs a valid jump
2) When inside of the file, press \<C-o\>.
3) Try to reproduce the first step from the same position and get error (E345: Can't find file "projects_controller.rb" in path).

The test line is:
get '/projekte/:id/:title' => "projects#show", as: 'public_project_show'
Command :nmap returns "n  gf           @<Plug>RailsFind"
The \<C-o\> has no mappings at all.
:pwd prints the proper project root path.

Everything becomes ok when i remove a 'view' file. Do you have any idea what it could be?

**Comment by tpope** [comment]
If I had to guess, `:set path?` is getting corrupted somehow. Check on success and failure.

**Comment by eugen0329** [comment]
Hmmmmm, really. I tried to comment each autocmd in my vimrc, and the result it was saving and loading views commands:
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview

I wonder how do this commands have corrupted the path option?

**Comment by tpope** [comment]
Not sure, but I've generally found views to suffer from lots of problems of that nature.
