### ISSUE TITLE
:Rake doesn't run the tests correctly if the test file in located in a "app" subdirectory

### ISSUE THREAD

**Issue by tbalthazar** [tpope/vim-rails#411]
I'm using Vim 7.4.576 on Debian and vim-rails is installed from master via Vim-Plug.
I've disabled every plugin but vim-rails.

In a brand new Rails 4.2.1 project, I have a test file in `test/integration/app/simple_app_test.rb`.
From there, if I type `:Rake`, I get the following message :
```
1 || rake aborted!                                      
2 || LoadError: cannot load such file -- /home/tb/Downloads/VimTest/test/integration/test/simple_app_test_test.rb             
3 -e|1| in `<main>'                                       
4 || Tasks: TOP => test:integration                       
5 || (See full trace by running task with --trace)
```
The problem can be seen on line 2 : the path is wrong.
It should be `test/integration/app/simple_app_test.rb` and not `test/integration/test/simple_app_test_test.rb`.
I guess the `app` part of the path confuses the vim plugin? (I have 2 other test files in `test/integration`, and the `:Rake` command works fine with them.)

Here is a sample Rails project if you want to reproduce the problem :
https://www.dropbox.com/s/ouy9mq9lmtl2yw4/VimTest.tar.gz?dl=0

**Comment by tbalthazar** [comment]
Thanks a lot for your fix.
The problem is solved when the test file is in `test/integration/app/simple_app_test.rb`, but not if it is in a subfolder, like this `test/integration/app/a_subdomain/simple_subdomain_app_test.rb`.
The error message is :
```
1 || rake aborted!
2 || LoadError: cannot load such file -- /home/tb/Downloads/VimTest/test/integration/test/a_subdomain/simple_subdomain_app_test_test.rb
3 -e|1| in `<main>'
4 || Tasks: TOP => test:integration
5 || (See full trace by running task with --trace)  
```
Here is the updated sample Rails project to reproduce the problem :
https://www.dropbox.com/s/gqlhrgfigu0poi4/VimTest2.tar.gz?dl=0

**Comment by tpope** [comment]
For legacy reasons, the `app` replacement can't easily be anchored to the start of the path.  The fix will have to wait for the alternates to be moved into the [default projections](https://github.com/tpope/vim-rails/blob/0bc3e59572bed70d5f5798bbf072887e4ae6f55c/autoload/rails.vim#L4532-4560).
