### ISSUE TITLE
E666: compiler not supported: rails

### ISSUE THREAD

**Issue by ipstatic** [tpope/vim-rails#414]
I just upgraded to vim-rails 5.2 (as well as vim-pathogen 2.3 and vim-bundler 2.0) and now I am getting the following error when opening any file inside of a Rails app:

```
Error detected while processing function rails#buffer_setup:
line   69:
E666: compiler not supported: rails
```
I have tried to very that vim can load my current Ruby environment as I use chruby and I believe it does.

`!ruby --version` returns my current ruby version of `ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]` and `:echo b:rails_root` returns my current Rails root.

Am I missing something?

**Comment by tpope** [comment]
Sounds like you are missing `compiler/rails.vim`, which should be included in the distribution.

**Comment by ipstatic** [comment]
Wow, somehow I lost that directory in-between an untar and a mv. Sorry for the noise.
