### ISSUE TITLE
Cannot create projection for "workers" directory

### ISSUE THREAD

**Issue by cvincent** [tpope/vim-rails#417]
I have a rather odd issue. This is with the latest release of vim-rails. I have the following custom projections set up:

```
let g:rails_projections = {
      \   "app/util/*.rb": {
      \     "command": "util",
      \     "template": "class %S\nend",
      \     "test": "spec/util/%s_spec.rb"
      \   },
      \   "app/lib/*.rb": {
      \     "command": "alib",
      \     "template": "class %S\nend",
      \     "test": "spec/lib/%s_spec.rb"
      \   },
      \   "app/workers/*_worker.rb": {
      \     "command": "worker",
      \     "template": "class %SWorker\n  include Sidekiq::Worker\n\n  def perform(*args)\n  end\nend",
      \     "test": "spec/workers/%s_worker_spec.rb"
      \   },
      \   "app/hooks/*_hook.rb": {
      \     "command": "hook",
      \     "template": "class %SHook\nend",
      \     "test": "spec/hooks/%s_hook_spec.rb"
      \   },
      \   "app/services/*.rb": {
      \     "command": "service",
      \     "template": "class %S\nend",
      \     "test": "spec/services/%s_spec.rb"
      \   },
      \   "app/serializers/*_serializer.rb": {
      \     "command": "serializer",
      \     "template": "class %SSerializer\nend",
      \     "test": "spec/serializers/%s_serializer_spec.rb"
      \   }
      \ }
```

Now if I try to create a new worker like this:

```
:Eworker foo!
```

I get the following error:

```
Error detected while processing function <SNR>119_Alternate..<SNR>119_find:
line    6:
E605: Exception not caught: Cannot create directory here
Error detected while processing function <SNR>119_Alternate:
line   14:
E171: Missing :endif
```

All my other projections worked, so I tried changing things around to identify specifically what was messing up the worker command. I discovered that just changing the directory from `workers` to something nonsensical like `wonkers` made the error disappear (great, except my new worker would be created in the `wonkers` directory):

```
      \   "app/wonkers/*_worker.rb": {
      \     "command": "worker",
      \     "template": "class %SWorker\n  include Sidekiq::Worker\n\n  def perform(*args)\n  end\nend",
      \     "test": "spec/wonkers/%s_worker_spec.rb"
      \   },
```

Very strange indeed.

**Comment by cvincent** [comment]
I also checked permissions on the `workers` directories (under both `app` and `spec`), and nothing was amiss there.

**Comment by cvincent** [comment]
One more detail that might be helpful. When the error occurs, I do end up with a new buffer in the proper path, but it's empty rather than pre-filled with the template. Just to make sure the template wasn't at fault, I made it the same as the other templates in my projections (which work), but the error persisted (and the buffer remained blank).

**Comment by tpope** [comment]
The problem is you are using a `!` when the file already exists. But it shouldn't blow up like that.

**Comment by cvincent** [comment]
Not sure how I missed that! Thanks!
