### ISSUE TITLE
How to override rails-projections for lib in vim-rails?

### ISSUE THREAD

**Issue by regedarek** [tpope/vim-rails#422]
my structure is like that:

    lib/managing_bookmarks/create.rb
    spec/use_cases/managing_bookmarks/create_spec.rb

I would like to add or override custom rails-projection behaviour like here: https://robots.thoughtbot.com/extending-rails-vim-with-custom-commands

I added to my .vimrc

    "lib/**/*.rb": {
      "command": "lib",
      "test": "spec/use_cases/%s_spec.rb",
      "related": "spec/use_cases/%s_spec.rb",
    }

But it doesn't work as expected. How to do that?

**Comment by tpope** [comment]
Don't use `**/*`. Also `%s` has been deprecated; use `{}` instead`.

**Comment by regedarek** [comment]
Thanks Tim.
