### ISSUE TITLE
Unable to use `Econtroller` with concerns

### ISSUE THREAD

**Issue by itspriddle** [tpope/vim-rails#424]
Since the switch to using projectionist for controller commands in 54d3c4fb, `Econtroller` is unable to open a concern under `app/controllers/concerns`. Any thoughts on a workaround?

**Comment by tpope** [comment]
Ugh, I know I was missing something. The best I can do short term is shove them in with the rest of the controllers.

**Comment by itspriddle** [comment]
:+1: thanks!
