### ISSUE TITLE
Elayout won't find application.html.erb

### ISSUE THREAD

**Issue by camador** [tpope/vim-rails#425]
'Elayout' (without param) does not generate the application layout path correctly (perhaps 'home..' instead of '/home...').

'Elayout application' works fine.

Thanks in advance.

**Comment by jonmast** [comment]
For me it is putting the base path twice i.e. /home/me/myapp/home/me/myapp/app/views/layouts/application.html.erb

**Comment by camador** [comment]
Many thanks :)
