### ISSUE TITLE
:A jump to test-unit not rspec

### ISSUE THREAD

**Issue by benoittgt** [tpope/vim-rails#426]
Hello

I'm on a project with rspec and old tests made on test-unit. I would like to now if it's possible to switch on the rspec tests first and not on the test-unit ? I've watch a little bit the plugin, vim-rails seems searching `*_test` before `*_spec`, try to edit it without success.

Thanks in advance.

**Comment by tpope** [comment]
Try some custom projections.

**Comment by benoittgt** [comment]
Thanks. I've tried something like 

```viml
" Prefere *_spec.rb rather than *_test.rb with :A
let g:rails_projections = {
      \  '*.rb': {
      \    'app/*.rb': {
      \       'alternate': 'spec/{}_spec.rb',
      \       'type': 'source'
      \     },
      \    'spec/*_spec.rb': {
      \       'alternate': 'app/{}.rb',
      \       'type': 'test'
      \     }
      \  },
      \}
```

But it still jump to `_test.rb` first. If someone have an idea.

**Comment by benoittgt** [comment]
Ok my fault. The answer is :

**Comment by tpope** [comment]
FYI you can leave off `'type': 'source'` unless you really want an `:Esource` command.

**Comment by benoittgt** [comment]
Thanks @tpope 💃
