### ISSUE TITLE
I think that this and all of your work is amazing.

### ISSUE THREAD

**Issue by chazubell** [tpope/vim-rails#429]
I may have had a loss of brain power but when you wrote "Once help tags have been generated, you can view the manual with :help rails."  I had forgotten that since I had installed your vim-pathogen I was at a loss as to what to do.  

However, I figured why not re-read the pathogen doc and there it was: *Provided with pathogen.vim is a :Helptags command that does this on every directory in your 'runtimepath'.*

Might I suggest that you add this to the vim-rails doc?

Thanks again for your wonderful tools.

-cdu

**Comment by tpope** [comment]
See the install instructions for fugitive.vim for my preferred solution to this. A PR to bring rails.vim in line would be great.
