### ISSUE TITLE
/bin/sh: 1: bundle: not found

### ISSUE THREAD

**Issue by ezuk** [tpope/vim-rails#430]
Hi there,

This plugin looks awesome. I'm trying to use it to run the current test:unit test I'm on. Here's what I do and what I get:

1) Open a test file such as test/renderers/example_test.rb
2) Go to one of the tests
3) Type :Rake
4) Get "/bin/sh: 1: bundle: not found"

Not quite sure why. Any ideas? 

Thank you!

**Comment by Haegin** [comment]
@ezuk Have you got the `bundler` gem installed? You'll probably need that to run the tests.

**Comment by ezuk** [comment]
@Haegin - I do have bundles. This is a fully configured Rails project, I can run rake from the command line.

**Comment by Haegin** [comment]
In that case, are you using chruby or something like that? If so I imagine the version of Ruby that Vim is loading doesn't have bundler installed, even though the version that you're developing with does.

**Comment by ezuk** [comment]
I know why it's happening now, just not how to fix it. Vim-rails assumes
bash; I use Fish, and all of my environment is set up with Fish. So I dont
need /bin/sh as the first command ,but fish. Any idea how I can set that up?

**Comment by tpope** [comment]
Rails.vim doesn't assume anything. It tells Vim to run a command, and Vim uses the `'shell'` option.

**Comment by ezuk** [comment]
Aha! Thank you, that helps. I'll look into changing that.

**Comment by ezuk** [comment]
Thanks Tim; when I set Fish as my shell, Vim explodes on startup with
"syntastic: error: your shell /usr/bin/fish can't handle traditional UNIX
syntax for redirections". Looking around, it seems like lots of other
things are going to explode in Vim if I just set Fish as my shell globally.

Is there a way to specify my shell just for Rails.vim?

**Comment by tpope** [comment]
No. My recommendation would be to maintain just enough of a Bash config to make it usable.
