### ISSUE TITLE
Overriding default projections no longer works

### ISSUE THREAD

**Issue by m1foley** [tpope/vim-rails#431]
In my `config/projections.json`:
```json
  "app/jobs/*_job.rb": {
    "command": "job",
    "affinity": "model",
    "test": "spec/jobs/{}_job_spec.rb",
    "template": "class {camelcase|capitalize|colons}Job < BaseJob\nend"
  },
```

Executing `:Ejob foo!` creates a file with the default projection:

```rb
class FooJob < ActiveJob::Base
end
```

It looks like 457006c is the last commit where this was working, so I'm guessing this was broken by d748823 or 9be6339.

**Comment by tpope** [comment]
Does using a list rather than a string fix it?

**Comment by m1foley** [comment]
No, changing it to this still doesn't pick up the template:

```json
  "app/jobs/*_job.rb": {
    "command": "job",
    "affinity": "model",
    "test": "spec/jobs/{}_job_spec.rb",
    "template": ["foo", "bar"]
  },
```

I've also tried adding `"type":"job",`, and removing the other attributes, all to no avail.

**Comment by tpope** [comment]
So one of the commits in question adds two new ways to fill in a template:

1. `:A app/jobs/foo_job.rb`
2. `:AD` in an existing file

Can you check both of those and see if either of them has the desired result? This will help me narrow it down when I have time to dig in.

**Comment by m1foley** [comment]
Both incorrect results:
1. `:A app/jobs/foo_job.rb` creates an empty buffer.
2. `:AD` in an existing file fills it in with the default template.

**Comment by m1foley** [comment]
Confirmed this works for me now. Thanks!
