### ISSUE TITLE
E/Rview doesn't expand with views directory

### ISSUE THREAD

**Issue by jandudulski** [tpope/vim-rails#436]
Either with controller `:Eview home/index.slim` or without `:Eview index.slim` - both expands to the path without `views` directory, e.g.: `/home/user/projects/example/home/index.slim` with error `E492: Not an editor command: /home/user/projects/example/home/index.slim`.

**Comment by tpope** [comment]
Can't reproduce, and that error is *really* strange. Forget the bad path, why is it interpreting the path as a command?

Check `:verbose command Eview` and see where the command was defined.

**Comment by jandudulski** [comment]
```
:verbose command Eview
    Name        Args       Address   Complete  Definition
  b Eview       *                    customlist    :execute s:viewEdit("E<bang>",<f-args>)
        Last setting by ~/dotfiles/Vim/_vim/bundle/rails/autoload/rails.vim
```

**Comment by tpope** [comment]
That looks fine; this may be tough to debug. Start with this:

1. Edit `autoload/rails.vim` and rename `s:viewEdit` to `RailsViewEdit`
2. Restart Vim and open a Rails project
3. `:echo RailsViewEdit('E', 'index.slim')`

**Comment by jandudulski** [comment]
`:echo RailsViewEdit('E', 'home/index.slim')` result in
`find /home/user/projects/example/home/index.slim`

**Comment by tpope** [comment]
Check `:echo rails#buffer().resolve_view('home/index.slim')`.

**Comment by jandudulski** [comment]
It returns nothing (with either original `s:viewEdit` and `RailsViewEdit`).

**Comment by tpope** [comment]
Well there's one problem. Do you even have that template?

**Comment by jandudulski** [comment]
> Do you even have that template?

Of course! But I debugged a little more and found out that it works fine for files ended `something.html.slim` or `something.html.erb` or whatever. It also works for `something.erb` or `something.haml` but... it doesn't work just for `something.slim`. Weird.

**Comment by tpope** [comment]
There is some special casing for a few extensions, but that's a holdover for pre-Rails 2 singular extension support, which in my understanding is still softly deprecated even if there are no plans to remove. `foo.html.erb` style naming has been standard since 2007. I can't imagine why you are still using it.

I would expect the "Clearer error" commit to incidentally fix your issue.

**Comment by jandudulski** [comment]
> I can't imagine why you are still using it

To be honest I don't see benefits to use redundant content type extension in between - the same with `.css.scss` or `.js.coffee`.

> I would expect the "Clearer error" commit to incidentally fix your issue.

It helps, thanks a lot!

**Comment by tpope** [comment]
`.js.coffee` and the like *are* deprecated, but as for views, it's hardly redundant, as you can use the middle extension for things like `.mobile.slim`, not to mention using slim to generate, say, XML, is not completely ridiculous. But really "I don't see the benefits" is a weak ass reason to break an established convention.
