### ISSUE TITLE
Rpreview problem with ipv6.

### ISSUE THREAD

**Issue by cenouro** [tpope/vim-rails#439]
My Debian came with this `/etc/hosts`:

    127.0.0.1       localhost
    127.0.1.1       debian
    # The following lines are desirable for IPv6 capable hosts
    ::1     localhost ip6-localhost ip6-loopback
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters

After running rails server, I can access the app root by going to `localhost:3000`, `127.0.0.1:3000` and `[::1]:3000` on my browser. But trying to use `:Rpreview`, I get this error:

    zsh:1: no matches found: http://[::1]:3000/

If I remove Ipv6 from `/etc/hosts`, `:Rpreview` works perfectly. To be honest, I don't care much about Ipv6. But `:Rpreview` should favor resolving `localhost` to `127.0.0.1` instead of resolving it to `[::1]`.

**Comment by tpope** [comment]
These 2 commits out to fix the shell escaping issue and try harder to favor the IPv4 address, respectively.
