### ISSUE TITLE
Eunittest with bang creates only helper tests

### ISSUE THREAD

**Issue by WojtekKruszewski** [tpope/vim-rails#440]
`Eunittest xxx!` creates `test/helpers/xxx_test.rb`. Is there a way to make it create model test?

(I'm using MiniTest)

**Comment by WojtekKruszewski** [comment]
Roundabout way is `Emodel xxx!` followed by `confirm A` but I'm looking for a convenient way to create test files first.

**Comment by tpope** [comment]
It's more of an accident than a feature but you can trick it with the following projection:

```
{
  "test/models/*_test.rb": {"type": "unittest"}
}
```

**Comment by WojtekKruszewski** [comment]
Whooha, projections rock! Thanks Tim.
