### ISSUE TITLE
:Elocale on same line

### ISSUE THREAD

**Issue by ylecuyer** [tpope/vim-rails#441]
It would be nice to allow to open another locale file on the same line used in the current file.

Current workflow:
```:Elocale fr -> look for key -> edit key -> :Elocale es -> look for key -> edit key```

In my case I know that every locale file has the same structure (using i18n-tasks)

Wanted workflow:

```:Elocale fr -> look for key -> edit key -> :Elocale# es -> edit key```

```:Elocale# [{name}]``` would jump to the locale file on the same line than the current edited file.

**Comment by tpope** [comment]
I think better than inventing an additional interface would be jamming it into `:R` using projections:

```json
{
  "config/locales/fr.yml": {"related": "config/locales/es.yml#{lnum}"},
  "config/locales/es.yml": {"related": "config/locales/de.yml#{lnum}"},
  "config/locales/de.yml": {"related": "config/locales/fr.yml#{lnum}"}
}
```

`{lnum}` was already supported for `"task"` projections so it was easy enough to add to `"related"`. Let me know if this doesn't address things.
