### ISSUE TITLE
Create alternate files

### ISSUE THREAD

**Issue by rstacruz** [tpope/vim-rails#443]
You can switch from model (`app/models/blorp.rb`) to tests (`spec/models/blorp_spec.rb`) easily using `:A`. However, when the test doesn't exist, `:A` will throw an error.

Can we perhaps allow `:A` to auto-create files? Maybe something like how projectionist does it where it shows you a prompt if it doesn't exist, or something like `:A!`.

**Comment by tpope** [comment]
It's currently experimentally supported with `:set confirm`.

**Comment by rstacruz** [comment]
how does that work? I used `:set confirm` then did `:A`—I'm still getting `E345: Can't find file "..." in path`.

**Comment by tpope** [comment]
What does `:echo rails#buffer().alternate_candidates()` reveal?

**Comment by rstacruz** [comment]
as `app/models/blorb.rb`, it echoes `['spec/models/blorb_spec.rb']`.

**Comment by tpope** [comment]
And `spec/models/` exists? Can you confirm you're on the latest?

**Comment by rstacruz** [comment]
yep! also, i'm on the latest master branch of vim-rails.

**Comment by tpope** [comment]
Oh, I see, I forgot it was only hooked up for alternates based on projections. Hence the "experimental" qualifier.  What needs to happen is alternates need to be moved out of https://github.com/tpope/vim-rails/blob/2c5c72aaf9711e53e4d54fbf8aee011e8e25ac82/autoload/rails.vim#L3268-L3368 where possible and into https://github.com/tpope/vim-rails/blob/2c5c72aaf9711e53e4d54fbf8aee011e8e25ac82/autoload/rails.vim#L4573-L4737. It's a massive task.

**Comment by rstacruz** [comment]
much respect to you for being able to maintain a single vimscript file with 5000 lines!
