### ISSUE TITLE
:A doesn't check app/lib

### ISSUE THREAD

**Issue by trevorrjohn** [tpope/vim-rails#445]
Hey I have some classes in my `app/lib` directory, but the navigation does not seem to like it and wont open the spec in `spec/lib/`. Any thoughts?

**Comment by tpope** [comment]
Setting aside the silliness of having both `app/lib` and `lib`, I would expect that to work (but the inverse might not). Assuming it still doesn't (there have been some changes in this area), a pull request would be great.

**Comment by graywh** [comment]
I think you can close this one.

**Comment by tpope** [comment]
Good enough for me.
