### ISSUE TITLE
gf switch to open buffer

### ISSUE THREAD

**Issue by sphynx79** [tpope/vim-rails#449]
I have this setting in my vimrc:
set switchbuf=usetab
because i use one tab for view one for controller and one for assets, with ctrlspace plugin i see only the buffers open in current tab.
Is possible gf command check if the buffer is open and switch this buffer.
Es:
TAB1 Controller
class Foo
   def index

   end
end

TAB2 View
index.haml is open

when gf in index method switch to TAB2 buffer index.haml

Thanks

**Comment by tpope** [comment]
From the `'switchbuf'` help, "It is also used in all buffer related split commands" so `<C-W>f` should do what you want.

**Comment by sphynx79** [comment]
Sorry but not work i try Ctrl+w+f but this open new buffer in same window

**Comment by sphynx79** [comment]
i try also edit your Rails.vim
nmap <buffer><silent> <Plug>RailsFind       <SID>:sb <Plug><cfile><CR>
and not work
but if insert in command line
:sb path_file
this work

**Comment by tpope** [comment]
Then you'll have to rig something up yourself. Hint: `:echo findfile(rails#cfile())`.

**Comment by sphynx79** [comment]
Thanks i insert:
function! GoBuf()
    let path_file = findfile(rails#cfile())
    execute ":sb "path_file
endfunction
map <F8> :call GoBuf()<CR>
and now work
