### ISSUE TITLE
javascript_tag or <script> syntax highlighting

### ISSUE THREAD

**Issue by jszmajda** [tpope/vim-rails#45]
It would be awesome to support javascript syntax highlighting correctly in inline script sections. Or am I doing something wrong?
Thanks!

**Comment by tpope** [comment]
Yes, although that doesn't cover making sure `<%= javascript_tag do %>` itself is highlighted correctly. 13 years later this doesn't seem that tricky; if `<script>` can do it I'm sure we can too.
