### ISSUE TITLE
Support for autoload_paths

### ISSUE THREAD

**Issue by zarelit** [tpope/vim-rails#450]
Rails loads models not only from the default paths but also from the paths in `config.autoload_paths` (`ActiveSupport::Dependencies.autoload_paths`)
It would be nice if vim-rails could look for models also in those paths.

Is it feasible?

**Comment by tpope** [comment]
You tell me. How can rails.vim find out you changed this?

I've never bothered to investigate because every addition to the load path I've ever been has been a subdirectory under `app/`, which rails.vim already autodiscovers.

**Comment by zarelit** [comment]
Unluckily the only "robust" way to do it is by calling the rails executable like this:
`rails r 'puts ActiveSupport::Dependencies.autoload_paths'`.
It is an expensive operation, compared to others (e.g. singularize), but maybe it could be included as a command or as an option.

**Comment by tpope** [comment]
Expensive and potentially dangerous, as we'd be running application code on buffer load, which could catch people by surprise. I think your best bet is to use a projection:

    {"*": {"path": ["my/directory", "another/directory"]}}

This isn't documented under `rails-projections` but probably should be.

**Comment by tpope** [comment]
I would also entertain a safe but hackish solution along the lines of statically extracting it from `config/application.rb`. But I won't be implementing it myself.

**Comment by zarelit** [comment]
I agree that for such specific cases configuring a projection could be the best solution. Thanks for you help :smiley:
