### ISSUE TITLE
Adding custom templates for Migrations

### ISSUE THREAD

**Issue by dkarter** [tpope/vim-rails#454]
We've come up with a need in our workflow to have more specific templates for migrations.

Specifically we want to generate the following template for migrations:

```ruby
class AddFooToBar < ActiveRecord::Migration
  def up
    execute <<-SQL
    SQL
  end
  
  def down
    execute <<-SQL
    SQL
  end
end
```

Looking through the vim-rails source code it seems relatively easy to extract the [`migrationEdit` template variable](https://github.com/tpope/vim-rails/blob/master/autoload/rails.vim#L2793) into a user configurable setting with a default to what it is right now and use a token for the class name.

I can submit a pull request for that if you think this is a welcome change. Would love to hear your thoughts.

Thanks!

**Comment by tpope** [comment]
I'd much rather see it integrated into projections, though I'm not sure the specifics of how that would work.

**Comment by dkarter** [comment]
Makes sense. So do you think adding something like `new_filename_template` option to projectionist will be a good idea?

That's the only thing missing so far. I was able to do everything else like so:

```json
{
  "db/migrations/*.rb": {
    "type": "migration",
    "template": [
      "class {camelcase} < ActiveRecord::Migration",
      "  def up",
      "    execute <<-SQL",
      "    SQL",
      "  end",
      "",
      "  def down",
      "    execute <<-SQL",
      "    SQL",
      "  end",
      "end"
    ]
  }
}
```

This is my proposed change:

```json
{
  "db/migrations/*.rb": {
    "type": "migration",
    "new_filename_template": "{timestamp}{}.rb"
    "template": [
      "class {camelcase} < ActiveRecord::Migration",
      "  def up",
      "    execute <<-SQL",
      "    SQL",
      "  end",
      "",
      "  def down",
      "    execute <<-SQL",
      "    SQL",
      "  end",
      "end"
    ]
  }
}
```

Also will projectionist override vim-rails if I have that installed or does that depend on loading order?

**Comment by tpope** [comment]
And what prevents the timestamp from appearing in `{camelcase}`? That's the real problem, after all, as we can continue hardcoding the timestamp expansion as that's not what you want to override.

Rails.vim always takes precedence over Projectionist.

**Comment by dkarter** [comment]
I'll try to think something up and submit a PR to Projectionist. Closing this. Thanks much!

**Comment by tpope** [comment]
"Rails.vim always takes precedence over Projectionist" means you would have to submit it here, not Projectionist.
