### ISSUE TITLE
Filetype not set to 'rails' on Neovim

### ISSUE THREAD

**Issue by dimascyriaco** [tpope/vim-rails#456]
Sorry if I'm doing something wrong here. I have the following config on my init.vim.

```
syntax on
colorscheme slate
call plug#begin('~/.config/nvim/plugged')
Plug 'tpope/vim-rails'
call plug#end()
```

I'm opening Neovim with a simple 'nvim' command.

The filetype is being set to 'ruby'. Shouldn't it be set to 'rails'?

ps.: The :Rails command works fine.

**Comment by tpope** [comment]
No, rails.vim doesn't change the filetype.

**Comment by dimascyriaco** [comment]
Ok. Thanks!
