### ISSUE TITLE
:.Rake on tests is broken in Rails 5

### ISSUE THREAD

**Issue by Xenofex** [tpope/vim-rails#471]
Hello,

The `:.Rake` on test is broken in Rails 5. For in Rails 5, invoking a single test file is like

```bash
# Rails 5
$ rake test TEST=test/models/card_test.rb
```

or

```bash
# Rails 5
$ rails test test/models/card_test.rb
```

Before, it was like
```bash
$ rake test:unit TESTOPTS="..."
```

as it is written in your current implementation.

**Comment by tpope** [comment]
Wait, so what is it doing for you now? `test:units`?

**Comment by Xenofex** [comment]
`rake test:units` is gone, no more. `rake test TEST=/path/to/test.rb` is all `rake test` supports (besides `rake test` to run all tests), only file, no path.

Basically `rake test` is the only command that `rake` can execute. They made `rails <cmd>` delegates to `rake <cmd>`, but this is not true - they actually migrated to `rails`, abandoning `rake` in the mean time. 

At least true for `rake test` - the recommended way to runt tests in Rails 5 is

```bash
$ rails test <file_or_folder_name>
```

Though it appears that from the updates of the [issue that I created](https://github.com/rails/rails/issues/26748), they reconsidered having some backward compatibility.

For now, I think it's good to make `rails test /path/to/test.rb[:line_no]` to run a single test in Rails 5.

**Comment by tpope** [comment]
I'm asking you to clarify what the current behavior is, not what the
desired behavior is. I already addressed this issue once.

**Comment by Xenofex** [comment]
`rake test:units` throws an error in Rails 5: no such command.

**Comment by tpope** [comment]
I know that. Are you saying calling `:.Rake` is doing that? Because it shouldn't, if it's correctly detected as a Rails 5 app.

* https://github.com/tpope/vim-rails/blob/7ea50ede5420058d3d5142d1a5d635ce876486cf/autoload/rails.vim#L1393-L1394
* https://github.com/tpope/vim-rails/blob/7ea50ede5420058d3d5142d1a5d635ce876486cf/autoload/rails.vim#L867

**Comment by Xenofex** [comment]
Yes I found the part that you mentioned above: detecting Rails 5 and run `rake test "/path/to/file"` for rails 5. Though this is not working. Because what you should run is `rails test "path/to/file"`, not the `rake` one.

**Comment by tpope** [comment]
For now, `:Rake` calls `rake`, and `:Rails` calls `rails`. I might get rid of `:Rake` entirely one day, I'm not sure.

**Comment by Xenofex** [comment]
Cool, thanks @tpope, for the tip and fix!

**Comment by caplod** [comment]
I have a brand new rails 5 app and when I call  `:.Rake` inside a test file it gives me:
```
Don't know how to build task 'test/models/film_test.rb:4' (see --tasks)
bin/rake test test/models/film_test.rb:4 
```
 
shouldn`t that be ?
```
bin/rake test TEST=test/models/film_test.rb:4
```

I have the latest vim-rails

**Comment by tpope** [comment]
It should be either what you say, *or* `bin/rails test test/models/film_test.rb:4`. The hybrid is wrong.

**Comment by tpope** [comment]
And to be clear, the fix I pushed should make `:.Rake` do `bin/rake test TEST=test/models/film_test.rb:4`, so make sure you are up to date.

**Comment by caplod** [comment]
I had vim configured with the janus distribution. 
Unfortunately it wasnt mentioned that vim-rails is already included (in a older version).
So vim was using the old version instead of the newer one.
Disabled the old version, now everything is working!!
Sorry for bothering you.

**Comment by house-owl** [comment]
Hey @tpope, seems like it might be a good time to deprecate :Rake.

While your fix works, seems like rake itself does not take the test file line into account:

```
 ⮀ rails test test/controllers/comments_controller_test.rb:10
Running via Spring preloader in process 8644
Run options: --seed 30304

# Running:

.

Finished in 0.714323s, 1.3999 runs/s, 1.3999 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

 ⮀ rake test TEST=test/controllers/comments_controller_test.rb:10
Run options: --seed 62444

# Running:

..

Finished in 0.815950s, 2.4511 runs/s, 2.4511 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

This is in Rails 5.0.2.

**Comment by tpope** [comment]
We could presumably bring back `TESTOPTS`, correct?

**Comment by house-owl** [comment]
@tpope As long as it still works, having this functionality would be very convenient. Might also make sense to make  `:Rails` and `:.Rails` with no arguments to fall back to running the tests, or is that a bad idea since rspec tests do not follow the same pattern?

**Comment by tpope** [comment]
I'm not sure what you're asking. Do you mean `:Rails` should fall back to running *all* tests in a context where we don't have a more specific task to do?

**Comment by house-owl** [comment]
Using the example above, I meant for `:Rails` to run

```
rails test test/controllers/comments_controller_test.rb
```

and `:.Rails` to run

```
rails test test/controllers/comments_controller_test.rb:10
```

Basically, having the same default functionality as `:Rake` and `:.Rake` currently have.

**Comment by house-owl** [comment]
In an unrelated note, I just pushed a little vimtutor-like tutor for rails.vim https://github.com/house-owl/vim-rails-tutor

Thank you for everything you do!

**Comment by tpope** [comment]
Oh, that was my intention, and it looks like my above `:Rake` fix may have broken things for `:Rails`? What is it currently doing for you?

**Comment by house-owl** [comment]
I am getting the following error when I run `:Rails` from a test, controller, or a model:

```
/Users/Admin/.gem/ruby/2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- /Users/Admin/test/vim-rails-tutor/TEST=test/models/comment_test.rb (LoadError)
	from /Users/Admin/.gem/ruby/2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/Admin/.gem/ruby/2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/Admin/.gem/ruby/2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/Admin/.gem/ruby/2.3.1/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:11:in `block in require_files'
	from /Users/Admin/.gem/ruby/2.3.1/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:10:in `each'
	from /Users/Admin/.gem/ruby/2.3.1/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:10:in `require_files'
	from /Users/Admin/.gem/ruby/2.3.1/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:86:in `plugin_rails_init'
	from /Users/Admin/.gem/ruby/2.3.1/gems/minitest-5.10.1/lib/minitest.rb:80:in `block in init_plugins'
	from /Users/Admin/.gem/ruby/2.3.1/gems/minitest-5.10.1/lib/minitest.rb:78:in `each'
	from /Users/Admin/.gem/ruby/2.3.1/gems/minitest-5.10.1/lib/minitest.rb:78:in `init_plugins'
	from /Users/Admin/.gem/ruby/2.3.1/gems/minitest-5.10.1/lib/minitest.rb:129:in `run'
	from /Users/Admin/.gem/ruby/2.3.1/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:72:in `run'
	from /Users/Admin/.gem/ruby/2.3.1/gems/minitest-5.10.1/lib/minitest.rb:62:in `block in autorun'
	from /Users/Admin/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Admin/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
Running via Spring preloader in process 12640
```

I see there is no space before `TEST=test...`, could that be it?

**Comment by tpope** [comment]
The problem is that `TEST=` is in there at all. Pushing what is hopefully a final solution for both `:Rake` and `:Rails`.

Now what I want to know is why `rails spec spec/controllers/comments_controller_spec.rb` doesn't work. (The `SPEC=` is still required there.)

**Comment by house-owl** [comment]
Great! Just pulled your new changes and gave them a shot. All works as expected. Thank you. 

I tried 

```
 ⮀ rails spec spec/models/user_spec.rb SPEC_OPTS="-e \"still works\""
/Users/Admin/.rubies/ruby-2.3.1/bin/ruby -I/Users/Admin/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/lib:/Users/Admin/.gem/ruby/2.3.1/gems/rspec-support-3.5.0/lib /Users/Admin/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Run options: include {:full_description=>/still\ works/}
.

Finished in 0.00333 seconds (files took 1.35 seconds to load)
1 example, 0 failures

 ⮀ rails spec SPEC=spec/models/user_spec.rb SPEC_OPTS="-e \"still works\""
/Users/Admin/.rubies/ruby-2.3.1/bin/ruby -I/Users/Admin/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/lib:/Users/Admin/.gem/ruby/2.3.1/gems/rspec-support-3.5.0/lib /Users/Admin/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/exe/rspec spec/models/user_spec.rb
Run options: include {:full_description=>/still\ works/}
.

Finished in 0.00256 seconds (files took 1.33 seconds to load)
1 example, 0 failures

⮀ rails spec SPEC=spec/models/user_spec.rb
/Users/Admin/.rubies/ruby-2.3.1/bin/ruby -I/Users/Admin/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/lib:/Users/Admin/.gem/ruby/2.3.1/gems/rspec-support-3.5.0/lib /Users/Admin/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/exe/rspec spec/models/user_spec.rb
..

Finished in 0.00332 seconds (files took 1.65 seconds to load)
2 examples, 0 failures

⮀ rails spec spec/models/user_spec.rb
/Users/Admin/.rubies/ruby-2.3.1/bin/ruby -I/Users/Admin/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/lib:/Users/Admin/.gem/ruby/2.3.1/gems/rspec-support-3.5.0/lib /Users/Admin/.gem/ruby/2.3.1/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
..

Finished in 0.00326 seconds (files took 1.49 seconds to load)
2 examples, 0 failures

```

Seems like `SPEC` is not required.

**Comment by tpope** [comment]
You have multiple spec files? It's definitely running the full suite when I give a filename.

**Comment by alanq** [comment]
Running :Rails or :.Rails in a test runs "rake test:units"
Not sure is it related to the above? vim-rails up to date

`:!bundle exec rake test:units TEST=test/models/../...rb
rake aborted!
Don't know how to build task 'test:units' (see --tasks)
Did you mean?  app:test:units
`

**Comment by tpope** [comment]
The new test tasks are used if either of the following is true:

* `app/assets/config/manifest.js` exists (generated by default on new Rails 5+ apps)
* bundler.vim reports a rails version of 5 or higher

Unfortunately this means false negatives if you don't have bundler.vim installed.

**Comment by alanq** [comment]
It works!
I just installed bundler.vim
And now I have bundler.vim (I didn't know it). Happy days, many thanks.
