### ISSUE TITLE
gf and :wincmd f produce different results

### ISSUE THREAD

**Issue by GabeIsman** [tpope/vim-rails#473]
Thanks for this awesome tool!

I noticed an oddity just now: in my setup `gf` correctly opens all sorts of files, for example `gf` with the cursor on `Tag` opens the right model.

However `:wincmd f` produces `E447: Can't find file "tag.find.rb" in path`.

Having this work correctly would be handy for bindings like `nnoremap gv :vertical wincmd f<cr>`.

**Comment by GabeIsman** [comment]
I was able to work around this with
`nnoremap gv :vsp <c-r>=findfile(rails#cfile())<cr><cr>`

**Comment by tpope** [comment]
`:wincmd` is a built-in and can't be extended. You can use `<C-W>f`.
