### ISSUE TITLE
Adding a hook / callback for Rrunner to execute user defined function.

### ISSUE THREAD

**Issue by alexanderjeurissen** [tpope/vim-rails#477]
I frequently use `Rrunner` capability to execute the nearest spec by providing a line number. In fact I created a `autocmd` command that automatically executes the nearest spec from the current line whenever I save a cucumber or rspec file.

```vimscript
  " Run specs under cursor if saving a rspec or cucumber file
  autocmd BufWritePost *._spec.rb :.Rrunner
  autocmd BufWritePost *.feature :.Rrunner
```

Often I work on a cucumber scenario or single context block and rerun that spec by saving, it would be a great help if Rrunner succeeds to have a way to hook into that so I can for example add a sign in the `signcolumn` stating that I already fixed that spec.

Currently I have to fallback to running the whole file use quickfix list to go the the next failing scenario fix it, run Rrunner and mark that line (I have a vim extension that highlights marks).

Ideally I would be able to define a vim function that gets executed after Rrunner completes:

```vimscript
function! s:on_rrunner_complete(parameters, exit_status)
endfunction
```

where parameters would be a hash and exit_status a boolean or int of some sorts.
Would you be open to a PR that implements said functionality ?

**Comment by tpope** [comment]
It should be possible to hook into `autocmd QuickFixCmdPost`, and check the value of `&l:makeprg` to get the executed command.

**Comment by alexanderjeurissen** [comment]
Wow that is an insanely quick reply 🚤 , thanks @tpope I'll look into this and come back to you on that.
