### ISSUE TITLE
]m move to next rspec describe or context block

### ISSUE THREAD

**Issue by alibby** [tpope/vim-rails#482]
Instinctively I motioned to go to the next describe block with ]m today and it didn't happen.
I was thinking that this seems a like a natural thing to have when in specs.  

Thanks, and thanks for the plugin.

**Comment by tpope** [comment]
I think `]M` for `describe`/`context` and `]m` for `it`/`specify` would make a lot of sense. But I don't think rails.vim is the place to do it. Really even taking ownership for spec syntax highlighting was a mistake.

Also implementing may be a pain, as we can't rely on the special `end` highlighting we get for `def`/`class`/`module`.
