### ISSUE TITLE
An error message when opening assets file

### ISSUE THREAD

**Issue by goozler** [tpope/vim-rails#485]
Hello! First of all, thank you for your legendary Vim plugins!

I started to get an error when I open a file
```
Error detected while processing function rails#buffer_setup[8]..<SNR>118_set_path_options:
line   10:
E716: Key not present in Dictionary: expr && cfilemap.buffer && cfilemap.rhs !~# 'rails#\|Ruby'
E15: Invalid expression: cfilemap.expr && cfilemap.buffer && cfilemap.rhs !~# 'rails#\|Ruby'
E716: Key not present in Dictionary: expr && cfilemap.buffer && cfilemap.rhs !~# 'rails#\|Ruby'
E15: Invalid expression: cfilemap.expr && cfilemap.buffer && cfilemap.rhs !~# 'rails#\|Ruby'
```

I'm bad at Vimscript, it's really hard to debug for me. I just found out:
1. It happens to not all files. But I get the error when I open a css, js, sass, etc. files from `/assets` folder
2. Before [that commit](https://github.com/tpope/vim-rails/commit/decbf71d637212165cbe873882b739ee18e9a7bf) everything works fine

I usually use Neovim but I have the same issue in Vim8 too.

If it's only on my side I'll try to find out a conflicting plugin or something like that. Let me know if you need more information about the issue, I'll try to help.

**Comment by tpope** [comment]
No problem, thanks for the bug report.
