### ISSUE TITLE
Rjavascript autocomplete for app/javascript folder for rails 5.1 + webpacker

### ISSUE THREAD

**Issue by suaron** [tpope/vim-rails#488]
I can't find a solution to enable autocomplete javascript files from app/javascript for Rjavascript command. 
Could you help me?
Thanks

**Comment by tpope** [comment]
I'm not really up to speed on the new webpacker stuff but my first instinct is that it should be a separate command. Maybe `:Epack`?

**Comment by suaron** [comment]
Thanks for idea!

```
let g:rails_projections = {
\    "app/javascript/*.jsx": {
\      "command": "pack"
\    }
}
```
