### ISSUE TITLE
:Eview bang doesn't create missing file

### ISSUE THREAD

**Issue by hayah** [tpope/vim-rails#489]
If I use `:Eview index!` in `users_controller.rb` it gives following error:
`E:172 Only one file name allowed: edit edit+AD app/views/users/index`
But `:Eview index.html.erb` works fine.

**Comment by tpope** [comment]
Note that rails.vim does not try to guess what extension you want when creating a view.

**Comment by m1foley** [comment]
This works if no extensions are provided (`:Eview index!`) but still broken if extensions are provided (`:Eview index.html.haml!`):

```
E172: Only one file name allowed:  edit edit+AD app/views/users/index.html.haml
```
