### ISSUE TITLE
Deep directories in projections

### ISSUE THREAD

**Issue by samstickland** [tpope/vim-rails#491]
Hi, great gem! It's already saving me a lot of time :)

I'm wondering if it's possible to use arbitrary levels of nesting in a projection. For example:

```
let g:rails_projections = {
      \ "app/concepts/**/cell/*.rb": {
      \   "command": "cell",
      \   "affinity": "cell",
      \   "alternative": "spec/concepts/**/cell/{}_spec",
      \   "related": "app/concepts/**/view/{}.slim"
      \ }
      \ }
```

This isn't working. The alternative *and* related commands continue to open the matching spec, which I believe is the default?

If there's a way to do this I'll write up the example in the wiki.

**Comment by tpope** [comment]
Use `{dirname}` and `{basename}`.

**Comment by samstickland** [comment]
Hi,

Thanks the reply.. however I think I'm misunderstanding something here :/

This config doesn't work:

```
let g:rails_projections = {
      \ "app/concepts/**/cell/*.rb": {
      \   "command": "cell",
      \   "affinity": "cell",
      \   "alternative": "spec/concepts/{dirname}/cell/{basename}_spec.rb",
      \   "related": "app/concepts/{dirname}/view/{basename}.slim"
      \ }
      \ }
```

However, if I try it with a specific directory name from my project, like below, then it does work:

```
let g:rails_projections = {
      \ "app/concepts/open_role/cell/*.rb": {
      \   "command": "cell",
      \   "affinity": "cell",
      \   "alternative": "spec/concepts/open_role/cell/{basename}_spec.rb",
      \   "related": "app/concepts/open_role/view/{basename}.slim"
      \ }
      \ }
```

**Comment by tpope** [comment]
So looks like `**/.../*` support is actually a projectionist.vim feature I never got around to porting over to rails.vim. Someone looking into that would be wonderful, though I'm guessing that won't be the most approachable of tasks to the uninitiated.

**Comment by akarzim** [comment]
@tpope Oh! I'm looking for that exact feature! Is anyone working on porting this useful projectionist.vim feature to rails.vim?

Subsidiary question: Why does rails.vim mimic the projectionist.vim features rather than calling projectionist.vim if the plugin is present?

**Comment by tpope** [comment]
Rails.vim's projections are older than Projectionist. The latter was inspired by the former.

**Comment by akarzim** [comment]
> Rails.vim's projections are older than Projectionist. The latter was inspired by the former.

It makes sense!
Thanks for the quick response and this useful plugin
