### ISSUE TITLE
'gf' leads to error E345 can't find file "<Plug>User.find_by_email" in path

### ISSUE THREAD

**Issue by Feuda** [tpope/vim-rails#492]
`user = User.find_by_email(email)  #rails code`

'gf' on the word 'User', it occured 

`E345 can't find file "<Plug>User.find_by_email" in path`

Any ideas?

**Comment by tpope** [comment]
Check `:verb cmap <Plug><cfile>`.

**Comment by Feuda** [comment]
@tpope  ouput as
`c  <Plug><cfile> &@rails#cfile()
        Last set from ~/.vim/bundle/vim-rails/autoload/rails.vim
Press ENTER or type command to continue`

**Comment by tpope** [comment]
That's correct. Can you check `:verb nmap gf`?

Also go ahead and report your exact Vim version.

**Comment by Feuda** [comment]
`:verb nmap gf` outputs 
<img width="880" alt="wx20170720-124400 2x" src="https://user-images.githubusercontent.com/436635/28401028-acf4828c-6d49-11e7-8e32-fac138695a73.png">
`:verb nmap <Plug>RailsFind` outputs
<img width="459" alt="wx20170720-124630 2x" src="https://user-images.githubusercontent.com/436635/28401037-bd2f1acc-6d49-11e7-8038-210a75c7ca30.png">

`vim --version` outputs
<img width="1106" alt="wx20170720-125449 2x" src="https://user-images.githubusercontent.com/436635/28401160-aa4f3058-6d4a-11e7-838c-f3e648125c0c.png">

**Comment by tpope** [comment]
I'm running out of ideas. Can you check what `<C-R><C-F>` does on the `:` command line? It should insert `user.rb`, but if it fails like `gf` it will insert `<Plug>User.find_by_email`. Go ahead and check `:cmap <C-R><C-F>` while you're at it.

**Comment by peyloride** [comment]
I have same problem. I check what you ask from @Feuda and my output same as him. But i did not understand your last request, @tpope. Forgive me, it just have been 1 weeks using vim.

I did try this command but `:<C-R><C-F>` it gaves an error: `E488: Trailing characters `

`:cmap <C-R><C-F>` outputs:
`c  <C-R><C-F>   @<Plug><cfile>`

**Comment by tpope** [comment]
Press CTRL-R CTRL-F on the command line.

**Comment by Feuda** [comment]
<img width="395" alt="wx20170809-122002 2x" src="https://user-images.githubusercontent.com/436635/29105248-368f3fbe-7cfe-11e7-91eb-1e775dada645.png">
<img width="215" alt="wx20170809-122158 2x" src="https://user-images.githubusercontent.com/436635/29105259-4588b752-7cfe-11e7-9ef5-1c58a9ae7224.png">

@tpope

**Comment by tpope** [comment]
The maps all look fine, so I think it's just an issue with the actual logic to determine the the filename. Can you try again on the latest? I've fixed a lot of bugs in that area. You can also check `:echo rails#ruby_cfile()` to make sure that matches up with the destination file.

**Comment by tpope** [comment]
Okay, that `<Plug>` in there is definitely something different happening. Can you report on these again?

    verbose cmap <Plug><cfile>
    verbose nmap gf

**Comment by Feuda** [comment]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/436635/42438071-93536c9e-8391-11e8-97a9-42ba613be797.png">
<img width="722" alt="image" src="https://user-images.githubusercontent.com/436635/42438097-a4164614-8391-11e8-859c-1e81644b40e9.png">
<img width="216" alt="image" src="https://user-images.githubusercontent.com/436635/42438137-bbe85b92-8391-11e8-8c45-68d9f8d906fa.png">
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/436635/42438158-c9df5db8-8391-11e8-9b45-069b0e3bc0be.png">
@tpope

**Comment by Feuda** [comment]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/436635/42487595-45c605ce-8434-11e8-8c03-3b83e8c82023.png">
<img width="518" alt="image" src="https://user-images.githubusercontent.com/436635/42487615-5bc88c8e-8434-11e8-8b7d-dacfb6f6c9e0.png">
@tpope

**Comment by tpope** [comment]
Those are fine. I'm out of easy things to check. Try stripping your config down to a minimal vimrc and rails.vim only, and see if you can still reproduce the problem.

**Comment by wail-fajr-rd** [comment]
Hello,
I had the same problem as in this ticket and try all the steps until I started stripping my config down.
I finally got "gf" to work after I removed "set paste".

**Comment by tpope** [comment]
`:set paste` is designed to *be* temporarily switched on before pasting something in your terminal. It disables a ton of Vim features, including auto-indenting and *all* insert mode and command line mode maps. Never, ever, ever, ever, ever, *ever* set it in your vimrc.

Thanks for sharing the results of your investigation. I wouldn't have thought to check for that otherwise.

**Comment by wail-fajr-rd** [comment]
Thanks for your explanation, I had no idea `:set paste` was this dangerous.
