### ISSUE TITLE
Commit f095e38 leads to errors in the `elm-vim` plugin

### ISSUE THREAD

**Issue by jweir** [tpope/vim-rails#493]
Commit https://github.com/tpope/vim-rails/commit/f095e38c5653f077 leads to error messages in the `elm-vim` plugin.  See https://github.com/ElmCast/elm-vim/issues/123

This only occurs for Elm code within a Rails project.

My vim script knowledge is too pathetic to understand if this is an issue with the `vim-elm` plugin or if `vim-rails` is doing something globally which could impact another plugin. 

Perhaps someone with better skills can help figure out the cause of this issue. 

Thank you

**Comment by tpope** [comment]
My guess is the lack of a `b:undo_ftplugin` in `ftplugin/elm.vim` is interacting poorly with rails.vim providing a default if it doesn't exist. Ideally vim-elm would add a `b:undo_ftplugin`, as that really is the best practice, but perhaps rails.vim should be handling that edge case differently.

**Comment by jweir** [comment]
Thank you for the explanation and direction.  I will work on getting the `elm-vim` plugin up to snuff.  

I am closing out this ticket since the elm-vim plugin is the source of the problem.
