### ISSUE TITLE
Gf command only looks for .rb files else errors

### ISSUE THREAD

**Issue by peyloride** [tpope/vim-rails#494]
Hello,

I have a similiar problem to this issue: https://github.com/tpope/vim-rails/issues/396
But that solution does not work for me. I think i have slightly different issue.

When i use gf on @internet_tariffs, it gaves me an error:
`E345: Can't find file "<Plug>internet_tariffs.last_page" in path `

My :nmap gf output:
`> n  gf           @<SNR>48_c:find <Plug><cfile><CR>`  

I can use :Emodel, :Eview etc.

I'm using it in Rails folder.

I have plugin/rails.vim and autoload/rails.vim under :scriptnames.

**Comment by tpope** [comment]
Similar to #396 but identical to #492 (note the `<Plug>`). Please followup on my outstanding questions there.
