### ISSUE TITLE
`Not an editor command Rnavcommand` when opening Rails project

### ISSUE THREAD

**Issue by PavelPenkov** [tpope/vim-rails#496]
I'm getting 

```
Error detected while processing User Auto commands for "Rails":
E492: Not an editor command: Rnavcommand step features/step_definitions -glob=**/* -suffix=_steps.rb

```

when opening any file in Rails project. Vim version 8.0.952, vim-rails 7206033fc2d7d53a531502ecd5a044ecdacc0354

**Comment by tpope** [comment]
That's from some other plugin. `:Rnavcommand` was recently removed but has been obsolete for years.
