### ISSUE TITLE
Suggestion: Eform & family

### ISSUE THREAD

**Issue by sodapopcan** [tpope/vim-rails#497]
It's very common for views to have a `_form` partial.  Sure, `:Evi _f<tab><cr>` isn't the worst thing ever, but it's a bit much for how often I want to invoke it.  Of course I made my own `Eform` command but it would be great to leverage auto-complete to easily jump to another controller's form by having it built-in to rails.vim.

I'd be more than willing to take on this task myself but I'm bringing it up here first as per your ask-before-you-patch policy.

**Comment by tpope** [comment]
Down that road lies `:Eindex`, `:Eshow`, `:Eedit`, etc, I don't think I want to walk it. Plus, it's not uncommon to have `app/forms/widget_form.rb` for Formtastic form builders or whatever, if we have `:Eform` by default we mess with that (imho more valuable) use case.
