### ISSUE TITLE
gf doesn't singularize for a render of instance variable with Rails-connected partial

### ISSUE THREAD

**Issue by seanhogge** [tpope/vim-rails#499]
For instance, if I have:

```Ruby
<%= render @books %>
```

then `gf` on the line (or on `@books`) looks for _books.html.erb in the correct directory. However, Rails wants _book.html.erb and does all its connector magic to controller and model such that the partial needn't have the loop, just the markup and insertion of the columns one wishes to display.

Unrelated: Thanks for the amazing work, this plugin has made learning Rails a delight.

**Comment by tpope** [comment]
This will require some juggling to fix, as some helper logic treats `render @books` and `render 'books'` identically.

**Comment by seanhogge** [comment]
Yeah, I was afraid of that. Another case of the price of convenience, I suppose.

I probably can't help much on the extensive codebase you're intimately familiar with, but if there is anything I can do that would be of use, I'm happy to chip in where I can.

**Comment by tpope** [comment]
Fixed this a little while back and forgot to close the issue.
