### ISSUE TITLE
`:syntax on` removes some RSpec syntax highlighting

### ISSUE THREAD

**Issue by astyagun** [tpope/vim-rails#501]
MacVim 8.0.1207 (140)

![sessions_controller_spec_rb____code_useradmin_spec_controllers__-_vim1](https://user-images.githubusercontent.com/158815/32232910-3334749e-be6a-11e7-94cb-27b22e24787f.jpg)

`:syntax on`

![sessions_controller_spec_rb____code_useradmin_spec_controllers__-_vim1](https://user-images.githubusercontent.com/158815/32233059-94e48300-be6a-11e7-9bb7-3b0a6aa3718e.jpg)

`:call rails#buffer_syntax()`

![sessions_controller_spec_rb____code_useradmin_spec_controllers__-_vim1](https://user-images.githubusercontent.com/158815/32232910-3334749e-be6a-11e7-94cb-27b22e24787f.jpg)

`:e`

![sessions_controller_spec_rb____code_useradmin_spec_controllers__-_vim1](https://user-images.githubusercontent.com/158815/32233059-94e48300-be6a-11e7-9bb7-3b0a6aa3718e.jpg)

Seems like `:syntax on` messes with syntax highlighting provided by the plugin. And `:syntax on` is called when my `.vimrc` is reloaded. I've fixed it by hiding the call to `syntax on` inside of `if !exists('g:syntax_on')` block. But I'm curious if there's a better solution.

**Comment by sj26** [comment]
I'm finding the same thing, but all the time. Here's an extract of `vim -V app/models/user.rb` for me with some `syntax` commands hacked in to dump during `rails#ruby_syntax()` and at the top and bottom of `/usr/local/share/vim/vim80/syntax/ruby.vim` (I also tried a local `~/.vim/bundle/ruby` checkout):

```
Executing FileType Auto commands for "*"
autocommand exe "set syntax=" . expand("<amatch>")
Executing Syntax Auto commands for "ruby"
autocommand if expand('<afile>:t') ==? 'gemfile' | call s:syntaxfile() | endif
Executing Syntax Auto commands for "ruby*"
autocommand if RailsDetect() | call rails#buffer_syntax() | endif
--- Syntax items ---
rubyAttribute  xxx mattr_accessor mattr_writer thread_cattr_accessor class_attribute thread_mattr_writer thread_mattr_reader mattr_reader attr_internal_reader cattr_accessor
                   thread_cattr_writer cattr_reader thread_cattr_reader attr_internal_writer cattr_writer attr_internal thread_mattr_accessor attr_internal_accessor
rubyMacro      xxx serialize accepts_nested_attributes_for has_secure_token delegate attr_readonly alias_attribute default_scope validate with_options concern scope
                   has_secure_password enum attribute store delegate_missing_to store_accessor concerning
rubyHelper     xxx logger
rubyEntity     xxx has_one belongs_to composed_of
rubyEntities   xxx has_and_belongs_to_many has_many
rubyCallback   xxx before_save after_destroy_commit after_initialize after_find before_update around_destroy after_update_commit after_create_commit after_destroy after_validation
                   before_validation after_touch around_update around_create after_commit after_rollback after_update after_create around_save after_save before_create
                   before_destroy
rubyValidation xxx validates validates_confirmation_of validates_acceptance_of validates_absence_of validates_size_of validates_uniqueness_of validates_with validates_format_of
                   validates_presence_of validates_each validates_numericality_of validates_length_of validates_inclusion_of validates_exclusion_of validates_associated
                   validates_associated
chdir(app/models)
fchdir() to previous dir
chdir(app/models)
fchdir() to previous dir
--- Syntax items ---
rubyAttribute  xxx mattr_accessor mattr_writer thread_cattr_accessor class_attribute thread_mattr_writer thread_mattr_reader mattr_reader attr_internal_reader cattr_accessor
                   thread_cattr_writer cattr_reader thread_cattr_reader attr_internal_writer cattr_writer attr_internal thread_mattr_accessor attr_internal_accessor
rubyMacro      xxx serialize accepts_nested_attributes_for has_secure_token delegate attr_readonly alias_attribute default_scope validate with_options concern scope
                   has_secure_password enum attribute store delegate_missing_to store_accessor concerning
                   links to Macro
rubyHelper     xxx logger
                   links to Function
rubyEntity     xxx has_one belongs_to composed_of
                   links to rubyMacro
rubyEntities   xxx has_and_belongs_to_many has_many
                   links to rubyMacro
rubyCallback   xxx before_save after_destroy_commit after_initialize after_find before_update around_destroy after_update_commit after_create_commit after_destroy after_validation
                   before_validation after_touch around_update around_create after_commit after_rollback after_update after_create around_save after_save before_create
                   before_destroy
                   links to rubyMacro
rubyValidation xxx validates validates_confirmation_of validates_acceptance_of validates_absence_of validates_size_of validates_uniqueness_of validates_with validates_format_of
                   validates_presence_of validates_each validates_numericality_of validates_length_of validates_inclusion_of validates_exclusion_of validates_associated
                   validates_associated
                   links to rubyMacro
Executing Syntax Auto commands for "*"
autocommand call s:SynSet()
Searching for "syntax/ruby.vim syntax/ruby/*.vim" in "~/.vim,~/.vim/bundle/*, (this line is cut off?)
Searching for "~/.vim/syntax/ruby.vim"
Searching for "~/.vim/syntax/ruby/*.vim"
...
Searching for "/usr/local/share/vim/vim80/syntax/ruby.vim"
chdir(/usr/local/share/vim/vim80/syntax)
fchdir() to previous dir
line 24: sourcing "/usr/local/share/vim/vim80/syntax/ruby.vim"
syntax/ruby
No Syntax items defined for this buffer
end syntax/ruby
--- Syntax items ---
rubySharpBang  xxx match /\%^#!.*/  display
                   links to Comment
rubyClass      xxx match /\<class\>/  nextgroup=rubyClassDeclaration skipwhite skipnl
(etc.)
```

It looks like `autocommand call s:SynSet()` is clearing existing syntax? Or the rails syntax additions are happening too early?

**Comment by sj26** [comment]
Ah! Maybe a fix, at least for my particular setup on vim 8.1 — and I think for `:syntax on` which seems to load `synload.vim` which has been causing m problems:

Add `~/.vim/syntax/ruby/rails.vim` containing:

```vim
if RailsDetect()
  call rails#buffer_syntax()
endif
```

@tpope is it possible to replace the Syntax autocmds with this?

**Comment by tpope** [comment]
@sj26 I'm guessing your config calls `:syntax on` after rails.vim is already loaded, making it basically the same as the original issue.

I am in fact moving towards using `syntax/ruby/rails.vim`, as it will *eliminate* the need for separate ERB and Haml modifications and is cleaner all around. I haven't pulled the trigger because `RailsDetect()` does IO and extra invocations can slow things down.

**Comment by tpope** [comment]
Okay, confession, I actually already the syntax file in my local worktree, and removing it breaks syntax highlighting for me too. Fuck, is it broken for everyone?

**Comment by sj26** [comment]
Ah, I’m using [sensible](https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim) which does a syntax enable... and “sensible” > “rails”... I’ll trying putting the syntax call straight in my vimrc.

**Comment by tpope** [comment]
Had not considered that. That's enough for me to up the priority of switching to after files.
