### ISSUE TITLE
:A changes working directory

### ISSUE THREAD

**Issue by ogirginc** [tpope/vim-rails#502]
When I am in a model file and run `echo @%`, I get `app/models/accounts.rb` as I expect. However, when I use `:A` to go to alternative, Vim opens it as `/Users/ogirginc/Developer/parasut/server
`. Is this suppose to happen (Got same result when I deleted all plugins except vim-rails)? 

![vim-alternative](https://user-images.githubusercontent.com/7466873/33019426-5f911d20-ce0b-11e7-83ee-1917ac063e74.gif)

**Comment by tpope** [comment]
It's not doing a `cd` but editing an absolute path. `:edit /Users/ogirginc/Developer/parasut/server` should have the same effect. Presumably could be fixed if you or someone cares to dig in.

**Comment by graywh** [comment]
I guess it's because `:A` often uses `:find` with an absolute path while some `:E` commands can use `:edit` with a relative path.

**Comment by tpope** [comment]
It's using `:find` as an easy way to get an error message when the file doesn't exist. It could certainly be changed (but lord, this code is a tangled mess).
