### ISSUE TITLE
exec bin/rake instead of bin/rails

### ISSUE THREAD

**Issue by amerov** [tpope/vim-rails#504]
![screenshot from 2017-12-06 14-41-22](https://user-images.githubusercontent.com/196747/33655034-ca1aac4e-da93-11e7-8793-b1ab2fe4ac9b.png)

**Comment by tpope** [comment]
What caused this?

**Comment by amerov** [comment]
@tpope I just call `:Rails g migration...`
if I call `:Rails generate migration`, it works
