### ISSUE TITLE
No output when I try to run tests

### ISSUE THREAD

**Issue by Ruffeng** [tpope/vim-rails#507]
Hi, 
When I try to run a test file with `Rails` I find all time that there's no output for my tests( see attached picture). I am not sure if I do something wrong, or I need extra plugins or gems ( I used to run Rspec in my terminal without any problem).
<img width="446" alt="screen shot 2018-01-24 at 10 02 00" src="https://user-images.githubusercontent.com/18511772/35325012-ca1ad9b4-00f2-11e8-847f-5cdceccbebad.png">

Any idea about what can it be...?

Thanks!

**Comment by tpope** [comment]
Try `rails spec SPEC=spec/..._spec.rb` (or `rake ...` for older Rails) in your terminal and see if that works.

**Comment by Ruffeng** [comment]
There is no output neither with this command.
with `rspec spec/..._spec.rb` it works, but from `rails spec` it's not rendering what I expect..

**Comment by tpope** [comment]
The `:Rails` command is, as the name suggests, hard coded to use the `rails` command, not `rspec`. I'm afraid you're on your own or debugging what's going wrong there. Maybe start by temporarily disabling Spring.
