### ISSUE TITLE
Calling `:Eview` from within a mailer method does not open view

### ISSUE THREAD

**Issue by vicramon** [tpope/vim-rails#511]
From within a normal controller method, calling `:Eview` opens the corresponding view file. But with mailers it does not work. 

For example, with a `UserMailer` class, it tries this path: `app/views/user/method_name` when it should be `app/views/user_mailer/method_name`. 

I would use this feature a lot if it existed.

**Comment by tpope** [comment]
Don’t those views go in `app/views/user_mailer`? I’m probably behind the times.

**Comment by vicramon** [comment]
Oh, they do, that's what I mean. Rails Vim is searching in `app/views/user` when it should be searching in `app/views/user_mailer`.

**Comment by vicramon** [comment]
I'm confused, is my issue wrong or is this just a no-fix?

**Comment by tpope** [comment]
Your issue was correct and should now be fixed.

**Comment by vicramon** [comment]
Oh sweet, thanks!
