### ISSUE TITLE
schemaEdit not picking up db/structure.sql

### ISSUE THREAD

**Issue by jc00ke** [tpope/vim-rails#515]
The current project I'm working on uses a `structure.sql` file instead of a `schema.rb`. Looks like `schemaEdit` [already handles](https://github.com/tpope/vim-rails/blob/39cb87dbbac742dad68908c1c645b8f202d8f943/autoload/rails.vim#L2842) when `schema.rb` is missing and `structure.sql` is present, yet I get an `E345 Can't find file /home/jesse/my/client/project/db/schema.rb`. I'm on 39cb87d.

Happy to help debug. Thanks!

**Comment by tpope** [comment]
Start by testing if those `has_file()` calls return what you expect.

**Comment by jc00ke** [comment]
By the time it gets to [this line](https://github.com/tpope/vim-rails/blob/39cb87dbbac742dad68908c1c645b8f202d8f943/autoload/rails.vim#L2852) `schema` is set to `db/structure.sql`

![image](https://user-images.githubusercontent.com/18191/38840454-955eeba6-4194-11e8-891c-6068a4c4f722.png)

`db/structure.sql` is opened but there's no automatic navigation to the `CREATE TABLE` line for the model name entered `:Eschema user`.

**Comment by tpope** [comment]
That's not implemented. Report back on what the create table declarations look like for the big 3 databases look like and we can assess how feasible it would be to implement.

**Comment by tpope** [comment]
P.S. here's PostgreSQL, since I have it handy:

    CREATE TABLE public.whatevers (

**Comment by jc00ke** [comment]
Just tried it out, works great, thank you! :tada:
