### ISSUE TITLE
gf is not mapped for slim templates

### ISSUE THREAD

**Issue by lisinge** [tpope/vim-rails#524]
gf works in .erb files.
`:nmap gf` in a .erb template gives `n  gf           @<SNR>214_c:find <Plug><cfile><CR>`

But it doesn't work in .slim files.
`:nmap gf` in a slim template gives `No mapping found`

**Comment by tpope** [comment]
In order for this to work, [Slim ftplugin](https://github.com/slim-template/vim-slim/blob/master/ftplugin/slim.vim) needs to load the Ruby ftplugin, as is done in [eRuby](https://github.com/vim-ruby/vim-ruby/blob/6959e10b399715418bcca90c4643da163fdb6330/ftplugin/eruby.vim#L89) and [Haml](https://github.com/tpope/vim-haml/blob/ac1cb44d58747ac70a4077da3796a9f696ee46a9/ftplugin/haml.vim#L37).

**Comment by lisinge** [comment]
Thank you @tpope. I had a feeling it would be something as simple as this. But my vimscript-fu was not strong enough to figure it out. So thanks for the clear instructions! I will open a issue in the correct repo.
