### ISSUE TITLE
Add highlights to embeds_one, embes_many and embedded_in

### ISSUE THREAD

**Issue by dareenzo** [tpope/vim-rails#527]
It'd be nice if highlights were added for `embeds_one, embeds_many` and `embedded_in` used in Mongoid, in the same way there are highlights for `has_one` and `has_many`

**Comment by kakas** [comment]
just define syntax highlight by yourself

```
let g:rails_projections = {
      \   "app/models/*.rb": {
      \     "rubyMacro": ["embeds_one", "embeds_many", "embedded_in"],
      \   }
      \ }
```
