### ISSUE TITLE
UltiSnips support

### ISSUE THREAD

**Issue by kleinjm** [tpope/vim-rails#531]
Would there be a way to include a `skeleton` key in the `rails_projections` so that the templates could be defined via ultisnips in `rails.snippets`?
ie.
```vim
let g:rails_projections =  {
  \   "spec/*.rb": {
  \     "command": "spec",
  \     "skeleton": "spec"
  \   }
  \ }
```
Perhaps there is already a way to stitch these tools together but I couldn't figure it out from [the documentation](https://github.com/tpope/vim-rails/blob/master/doc/rails.txt#L657). Thanks in advance, Tim

**Comment by srydell** [comment]
You can do exactly that with [vim-skeleton](https://github.com/srydell/vim-skeleton), which uses tpope's vim-projectionist and Ultisnips in the background. Hope that helps!

**Comment by tpope** [comment]
Sounds good to me!
