### ISSUE TITLE
[Feature Request] :Efactory

### ISSUE THREAD

**Issue by nintF1link** [tpope/vim-rails#533]
I think that is a good idea add a shortcut to edit factories, btw with `:Espec factories/factory.rb` does not work :c
And `:Eroutes` and `Eapplication` (or `:Econfig` simply)

**Comment by tpope** [comment]
You can use `:Efixtures` to access factories. I don't think FactoryGirl, a popular but by no means standard library, should be given a namesake command in core (but you can create your own with projections).

You can use `:Einitializer` and `:Eenvironment` to access `config/routes.rb` and `config/application.rb`, respectively. My personal taste is this is cleaner than having a bunch of one-off commands for one-off config files.

**Comment by nintF1link** [comment]
@tpope `:Efixtures` works fine to edit factories, but neither `:Einitializer` nor `:Eenvironment` works to access `config/routes.rb` or `config/application.rb`

**Comment by tpope** [comment]
Call them with no argument.
