### ISSUE TITLE
vim-rails overrides makeprg value

### ISSUE THREAD

**Issue by itsNikolay** [tpope/vim-rails#535]
## Issue
`vim-rails` overrides `makeprg` value
## Steps to reproduce:
1. .vimrc:
```vim
comp rails
set makeprg=bin/rspec " I expect rspec
```
2. in vim:
```vim
:set makeprg
makeprg=bin/rails  " I get rails
```
## Evironment
vim-rails version: cb188c6b73d490d3e9b2e3ada044e208aabdc647
vim version: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 25 2019 16:45:07)
macOS version
Included patches: 1-982
```

**Comment by tpope** [comment]
Use `autocmd User Rails ...` to override the compiler.

**Comment by martinos** [comment]
I am not sure I understand. 

In this case should we do :

```
autocmd User Rails makeprg=bin/rspec

```
?

**Comment by tpope** [comment]
```vim
autocmd User Rails compiler rspec
```

**Comment by ylecuyer** [comment]
For future reference, looks like the event is now called BufEnterRails https://github.com/tpope/vim-rails/blob/959e94b76e6ebdf984acef61649ba7d0f62bd425/plugin/rails.vim#L111

So it is: `autocmd User BufEnterRails compiler rspec`

**Comment by tpope** [comment]
The event wasn't renamed; that's a different event.
