### ISSUE TITLE
Keep jumps when jumping within schema after invoking `:R`

### ISSUE THREAD

**Issue by sodapopcan** [tpope/vim-rails#542]
Would it be possible to not add to the jumplist twice when calling `:R` on a model?  I often prefer to hit `<C-O>` to keep the schema out of my jumplist and I currently have to hit it twice (once jumps to the top of the file and then again to get back to the model). It's a minor annoyance for sure, but wondering if you would be open to this change.

Thanks!

**Comment by tpope** [comment]
I think adding `keepjumps` to the `djump` invocations would probably be fine.

**Comment by sodapopcan** [comment]
Oh nice, that's cool :)  Is that something you'd like me to make a PR for or would you prefer to do it?

**Comment by tpope** [comment]
Please confirm it works and make a PR.

**Comment by sodapopcan** [comment]
Cool, I'll run it locally for a week or then make a PR.

Thanks!
