### ISSUE TITLE
gf works but ctl-W-gf fails

### ISSUE THREAD

**Issue by benlieb** [tpope/vim-rails#544]
The most useful version for me of gf is to open in a new tab, but for some reason this fails for me, whereas the other versions offered of gf (ctl-w-ctl-f, etc) do work. Is this generally broken or do I have some conflicting setting somewhere?

**Comment by benlieb** [comment]
Ok, looks like my issue was using ctl-w instead of ctl-W...

**Comment by tpope** [comment]
There shouldn't be a difference between the two, that is, holding the shift key should have no effect.

One plausible explanation is typing speed, as you have to press all 3 keys within 1 second for the map to take effect.

**Comment by benlieb** [comment]
Hm, looking again, I can see that you are right. I think I was doing the my old habit of gF instead of gf. That's a hang-over. Thanks for your suggestion... sorry to waste your time on doing wrong...
