### ISSUE TITLE
File type of non-Rails YAML files become eruby.yaml

### ISSUE THREAD

**Issue by ryym** [tpope/vim-rails#545]
Hi, thank you for the awesome plugin!

### Problem

When I open a YAML file in Rails repository, this plugin automatically sets the `filetype` of it as `eruby.yaml` instead of `yaml`, even if the file has nothing to do with Rails. For example:

- [docker-compose.yml][docker-compose-yml]
- [.circleci/config.yml][circleci-config-yml]
- [.travis.yml][travis-yml]

These files' `filetype` are set to `eruby.yaml`. And the problem is that the default `commentstring` is different between `eruby.yaml` and `yaml` file type:

- `eruby.yaml` - `<%#%s%>`
- `yaml` - `# %s`

Since the comment format of `eruby` is invalid in YAML, we cannot comment out code easily in a normal YAML file with `eruby.yaml` type by [`vim-commentary`][vim-commentary] which depends on the `commentstring` option.

[circleci-config-yml]: https://circleci.com/docs/2.0/configuration-reference/
[travis-yml]: https://docs.travis-ci.com/user/tutorial/
[docker-compose-yml]: https://docs.docker.com/compose/overview/
[vim-commentary]: https://github.com/tpope/vim-commentary

### Suggestion

How about setting the `filetype` of YAML files in the general Rails directories only?
Such as `app`, `lib`, `config`, `test`, and `spec`.

(code link):

https://github.com/tpope/vim-rails/blob/8407484a329b6722ee088a096a8d879a5c32ac67/plugin/rails.vim#L100-L103

**Comment by tpope** [comment]
Makes sense. I think config files and fixtures cover all the use cases.

**Comment by ryym** [comment]
Thank you for the quick fix!
