### ISSUE TITLE
Support AsyncRun

### ISSUE THREAD

**Issue by skyksandr** [tpope/vim-rails#546]
First of all - Thank you for your work on it @tpope! I very appreciate it!

I was looking through docs and code and haven't got an idea on how to replace `vim-dispatch` with https://github.com/skywind3000/asyncrun.vim

If it's possible - could you point me to the direction? If not - will appreciate if you point me to the relevant piece of code, so I can cook a PR.

**Comment by tpope** [comment]
We call `:Make` if available and `:make` if not. While Dispatch provides `:Make`, you can also provide your own that calls asyncrun or whatever.

Note that Dispatch finally got job support literally a few days ago, so you may find it now suffices for your needs.
