### ISSUE TITLE
Extend 'path' through custom projections

### ISSUE THREAD

**Issue by toupeira** [tpope/vim-rails#548]
I have some custom projections in a `.projections.json` file and would like to support the `gf` command for them as well. Currently I get an error `E345: Cannot find file "..." in path`, but after doing `set path+=...` it works as expected.

Is there a way to extend `path` through the custom projections, or could you maybe add the `dirname()` of all keys automatically?

**Comment by tpope** [comment]
```json
{
  "*.rb": {"path": "lib"}
}
```

**Comment by toupeira** [comment]
Thanks! Should have checked the docs for `vim-projectionist` as well... :see_no_evil:
