### ISSUE TITLE
Some version of Vim this year broke the use of range with `:'<,'>Rails`

### ISSUE THREAD

**Issue by emilyst** [tpope/vim-rails#549]
Sometime earlier this year (I wanna say in spring?), the use of the default `:Rails` command using a range broke.

The behavior before was that, in a spec file (for example), I could select a line and type `:'<,'>Rails`, upon which it would pass that to the spec runner. This behavior is intact in Vim 8.0.1365 (default on Mojave).

On Vim version 8.1.2100 (from Homebrew), running that command gives the error message, `E16: Invalid range`.

I made some considerable effort to bisect the vim-rails and vim-projectionist and vim-dispatch plugins to discover if they had a regression. I could not find one. This appears to be a change in Vim itself. I cannot for the life of me figure out which patch caused this or what the actual problem is. Sorry about that.

**Comment by tpope** [comment]
In the same ballpack as https://github.com/tpope/vim-scriptease/issues/43 and https://github.com/tpope/vim-fugitive/issues/1358. These backwards incompatible changes are very out of character; not sure what the story is there.

This particular case is a rather awkward use of `-count` that needed to be cleaned up anyways, so no loss there.

**Comment by emilyst** [comment]
> In the same ballpack as [tpope/vim-scriptease#43](https://github.com/tpope/vim-scriptease/issues/43) and [tpope/vim-fugitive#1358](https://github.com/tpope/vim-fugitive/issues/1358). These backwards incompatible changes are very out of character; not sure what the story is there.
> 
> This particular case is a rather awkward use of `-count` that needed to be cleaned up anyways, so no loss there.

Tough but fair.
