### ISSUE TITLE
Not an editor command: EVmodel

### ISSUE THREAD

**Issue by artemave** [tpope/vim-rails#550]
Hello,

`Emodel` works just fine, but `EVmodel` (as well as `ES`, `ET`, etc.) does not. Same goes for controllers. What am I doing wrong?

I am using the latest version on neovim.

Thanks!

**Comment by tpope** [comment]
`:Vmodel`

**Comment by artemave** [comment]
Thanks! Somehow I am stuck with the old version of `:help rails` - still shows `Rmodel`, etc.
