### ISSUE TITLE
:Generate tries to edit file with windows newline

### ISSUE THREAD

**Issue by f1sherman** [tpope/vim-rails#556]
Hello! When I use `:Generate` to create a migration, it tacks a windows newline (`^M`) on to the end of the file it opens in the editor for some reason. I'm on MacOS. Since I don't see any other reports about this I'm assuming it's just me. Any ideas why this might happen?

Example: `:Generate migration MyMigration` generates the migration correctly and then edits a file with the name `db/migrate/20200425175214_my_migration.rb^M`, which does not exist. The generated file itself is fine (no `^M` in the filename), it's just the editor that gets the filename wrong.

Thank you!

**Comment by tpope** [comment]
Weird. Can you try on a brand new Rails project, to make sure some dependency isn't having a strange side effect?

**Comment by f1sherman** [comment]
@tpope you're right, it must be something with this specific rails app. I tried with a new app on the same machine and it worked just fine. Any ideas where to start looking to track that down? Thank you!

**Comment by tpope** [comment]
Dependencies!
