### ISSUE TITLE
"confirm + nav command" file creating function regression

### ISSUE THREAD

**Issue by bootleq** [tpope/vim-rails#559]
The experimental feature `:confirm A` to create non-existing Alternative file, was broken since https://github.com/tpope/vim-rails/commit/097a565.

The result of `matchstr` of `"confirm A"` was `A` but became `confirm A`.

Eventually, it produces `E464: Ambiguous use of user-defined command` due to execute `confirm A`.

**Comment by benoittgt** [comment]
I confirm that reverting this commit make it work again. In vim plug I have now this:

```
Plug 'benoittgt/vim-rails', { 'branch': 'revert-097a565' } " revert ':confirm A' issue
```
