### ISSUE TITLE
Unable to override default projections

### ISSUE THREAD

**Issue by kleinjm** [tpope/vim-rails#562]
I'm trying to override the default projection for `spec/models` and cannot figure out how to get the override to work. I have set all three of these global configs to the following
```
let g:rails_projections = {
      \    "spec/models/*_spec.rb": {
      \      "affinity": "model",
      \      "template": [
      \        "# frozen_string_literal: true",
      \        "",
      \        "require \"rails_helper\"",
      \        "",
      \        "RSpec.describe {camelcase|capitalize|colons} do",
      \        "  describe \"\" do",
      \        "  end",
      \        "end"
      \      ],
      \      "type": "unit test"
      \    }
      \ }
let g:rails_gem_projections = { same as above }
let g:projectionist_heuristics = { same as above }
```
as well as set the following in my project's `config/projections.json`
```
{
  "spec/models/*_spec.rb": {
    "affinity": "model",
    "template": [
      "# frozen_string_literal: true",
      "",
      "require \"rails_helper\"",
      "",
      "RSpec.describe {camelcase|capitalize|colons} do",
      "  describe \"\" do",
      "  end",
      "end"
    ],
    "type": "unit test"
  }
}
```
I'm still getting the following when I run `:Espec models/doc_news/local!`
```rb
require 'rails_helper'

RSpec.describe DocNews::Local, type: :model do
end
```

**Comment by bpinto** [comment]
I think I'm experiencing a similar issue, I've got global projections configured but they are overridden by `vim-rails`:

```
# init.vim

let g:projectionist_heuristics = json_decode(join(readfile(expand('~/.config/projections.json'))))
```

```
# projections.json

{
  "front-end/": {
    "*.js": {
      "alternate": "{}.test.js"
    },
    "*.test.js": {
      "alternate": "{}.js"
    }
  }
}
```

```
# /src/app/front-end/pages/index.js

::echo projectionist#query("alternate")
[['/src/app', 'front-end/pages/index.test.js']]

:A
E345: Can't find file "/src/app/front-end/pages/index_spec.js" in path
```

**Comment by tpope** [comment]
The original example defines a template for `:Eunittest`, *not* `:Espec`. Templates are tied to the command name in rails.vim; I fixed this mistake in projectionist.vim, but rails.vim hasn't been retooled to use projectionist.vim, as this is a massive task.

And because rails.vim has its own projection system, you can't mix and match them. rails.vim override anything it conflicts with in `g:projection_heuristics`. I would love to fix this, but once again, massive task.
