### ISSUE TITLE
Support rake notes task

### ISSUE THREAD

**Issue by eloyesp** [tpope/vim-rails#567]
I've just found that when running `:Rails notes` the `errorformat` does not seems to match those notes. It does not seems to be a super important adittion, and I'm not sure how difficult could be doing that (I've been reading about the errorformat without much luck, I can try a pull-request myself if someone tell me that the format makes it possible).

The format of the message is:

```
app/models/post.rb:
  * [ 67] [TODO] suffers :reek:DuplicateMethodCall and :reek:FeatureEnvy

app/models/board.rb:
  * [ 10] [TODO] should do other stuff instead

app/models/todo.rb:
  * [ 16] [TODO] abstract this out
  * [ 54] [TODO] missing test for uniq call
```

Regards.

**Comment by eloyesp** [comment]
I've just checked and it seems to work fine when run like: `:Rake notes`

**Comment by tpope** [comment]
This should really be fixed to work for `:Rails notes` too.

**Comment by tpope** [comment]
P.S.  Rails can go fuck itself for using such an asinine format.
