### ISSUE TITLE
Anyway to disable vim-rails command output to shell?

### ISSUE THREAD

**Issue by Vizkrig** [tpope/vim-rails#569]
Please see below the example (`:Rails about`) command.

![command](https://user-images.githubusercontent.com/7304350/100533336-2625ee00-3229-11eb-8996-9e07c0364de4.png)

Once I press enter vim redirects to the shell to show the output.

![shell-output](https://user-images.githubusercontent.com/7304350/100533359-78670f00-3229-11eb-9f61-fe7da90745bd.png)

Then I come back to vim by pressing `Enter`. Afterwards I'm greeted with another output from vim itself, please see screenshot below

![vim-output](https://user-images.githubusercontent.com/7304350/100533367-8ddc3900-3229-11eb-9fe0-336782d5bbf8.png)

I'm happy with the command output inside vim itself. Is there anyway to disable the shell output for the Rails commands?

Please note that I still want to use shell commands (example `!ls`)

**Comment by tpope** [comment]
Installing dispatch.vim will effectively achieve the behavior you desire.
