### ISSUE TITLE
Question (or feature request): Navigate to parent partial 

### ISSUE THREAD

**Issue by cIvanrc** [tpope/vim-rails#572]
Hi
quick question, there is a way to go back or list the files where the current partial was called??

Example:

If a partial is called in just one file:
> jump directly to the file where the render was made

If a partial is called in more than one file:
> list the `n` files where the partial could be rendered, and be able to jump to the select one

**Comment by tpope** [comment]
The Vim primitives `CTRL-O` and `CTRL-^` are useful in different ways for navigating back. There isn't really a good way to find where a partial is used other than by grepping for it, and rails.vim doesn't provide anything to assist with this.
