### ISSUE TITLE
Could gf create new file instead of error that it does not exist?

### ISSUE THREAD

**Issue by jdsutherland** [tpope/vim-rails#575]
Use case: adding a new controller without generator from routes.rb:
```ruby
resources(:sold_out_concerts) # gf => E345: Can't find file "sold_out_concerts_controller.rb" in path
```

If `gf` could be configured to create the file, this would save some keystrokes. Looking at https://github.com/tpope/vim-rails/issues/503, perhaps `:set confirm` could be the option?

**Comment by tpope** [comment]
`gf` is way more liberal about where it can jump than even alternates is. It can edit files inside gems for example. I think this is a non-starter.
