### ISSUE TITLE
gf command does not look for .html.erb extension when used on collection variables

### ISSUE THREAD

**Issue by kulbirsaini** [tpope/vim-rails#586]
Vim: 8.1.2269
Vim Rails: 9c92dafe6894aed3fa81df7ac52cdd8e7a8ea9a6 [May 05, 2022]
Ruby: 3.1.2
Rails: 7.0.2

As per title, the `gf` commands works fine everywhere except when you are on the ~~instance~~ collection variables. In that case, it somehow does not look up for `.html.erb` extension. A screenshot is attached.

![vim-rails-bug](https://user-images.githubusercontent.com/127315/168266055-dfb32cad-4894-40cd-9d18-2e7afd61d53e.png)

**Comment by tpope** [comment]
`'suffixesadd'` takes care of `.erb`. The problem is `_industries` vs `_industry`.

**Comment by kulbirsaini** [comment]
Ah! You are right. The plugin is not able to handle collection renders. Tried with another controller `<%= render @sectors %>` and same issue. I am not sure if this is something that the plugin can handle in future.
