### ISSUE TITLE
`let` syntax highlighting not using rubyTestMacro group

### ISSUE THREAD

**Issue by rickydalziel** [tpope/vim-rails#591]
It looks like [this](https://github.com/tpope/vim-rails/commit/83e17679f82e526c55e0d670ef0ad8d97a5fd4f5) commit has broken the highlighting on `let` blocks. I think it's maybe broken some other things too like the `describe` in  `Rspec.describe` no longer highlighting correctly.

Before:
![image](https://user-images.githubusercontent.com/3370118/189943699-4b45c56d-4882-4b60-965d-2645c36cb081.png)

With the newest version:
![image](https://user-images.githubusercontent.com/3370118/189943153-913191f9-313f-41fd-ba5f-230c5f538f8b.png)

**Comment by tpope** [comment]
Found an issue with `RSpec.describe`. For the `let` issue please report back on the value of `:verbose set iskeyword?`. My guess is it's been moneyed with.

**Comment by rickydalziel** [comment]
Just ran that command, here's the output:

`iskeyword=@,48-57,_,192-255`

**Comment by tpope** [comment]
That's the correct value. You may be on your own to debug this. I'd start by trying with `do`/`end`, and then again with a parentheses-free syntax.

**Comment by rickydalziel** [comment]
Ok, thanks for your help!
