### ISSUE TITLE
*rails-projection-test* does not serves as a default for "alternate"

### ISSUE THREAD

**Issue by jiz4oh** [tpope/vim-rails#593]
As described in the document, "test" will be used as a default for "alternate". 

<img width="779" alt="image" src="https://user-images.githubusercontent.com/41264693/200106839-cb7b1c79-f9bd-4538-8bf6-f68a3b67898e.png">

Generally, it is effective. But it is invalid with `:confirm A`, e.g.

```vim
let g:rails_projections = {
      \  "app/controllers/*_controller_decorator.rb": {
      \    "command":  "controller_decorator",
      \    "affinity": "controller",
      \    "test": "spec/requests/{}_controller_spec.rb",
      \ }
      \}
```

When I call `:confirm A` in a file names `app/controllers/spree/admin/orders_controller_decorator.rb`, it raise the error.

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/41264693/200107117-ffbcc636-8cd3-4a8b-aea6-a7237e0ec625.png">

But, if I set "alternate"  explicitly

```vim
let g:rails_projections = {
      \  "app/controllers/*_controller_decorator.rb": {
      \    "command":  "controller_decorator",
      \    "affinity": "controller",
      \    "alternate": "spec/requests/{}_controller_spec.rb",
      \    "test": "spec/requests/{}_controller_spec.rb",
      \ }
      \}
```
<img width="960" alt="image" src="https://user-images.githubusercontent.com/41264693/200107097-85fac819-0613-4fe1-bade-466073ed7c91.png">

It's worked now.

PS: `A` command works nice when alternate file is present regardless if "alternate" is specified. Only `:confirm A` is broken

Hi @tpope, is this intentional or a bug?

**Comment by tpope** [comment]
It's one of the reasons the feature is considered experimental. Very unclear where exactly to draw the line.
