### ISSUE TITLE
Call vim-rails commands in neovim using <Plug>

### ISSUE THREAD

**Issue by dgdosen** [tpope/vim-rails#594]
Say I wanted to remap the rails-vim |gf| command in neovim,  I'm thinking I should be able to call  something like `<Plug>(rails-vim)gf`

Should that work?

**Comment by tpope** [comment]
No, you'll need to do what rails.vim does and invoke the `<Plug><cfile>` map as an argument to `:find`:

https://github.com/tpope/vim-rails/blob/959e94b76e6ebdf984acef61649ba7d0f62bd425/autoload/rails.vim#L4850-L4854

The `<SID>:` thing effectively translates `2gf` into `:2find <Plug><cfile>`. You'll need to do something similar (or skip it, as you probably don't normally use a count anyways).
