### ISSUE TITLE
[Feature Request]Expose the s:map_gf to customize gf

### ISSUE THREAD

**Issue by jiz4oh** [tpope/vim-rails#597]
Hi @tpope, thank you for creating the awesome plugin, I have a bit feature request, could you please expose the `s:map_gf` function that let user can customize the [gf map](https://github.com/tpope/vim-rails/blob/1ad9663ce31e8c08134849d04184cda94bb42aba/autoload/rails.vim#L4839), so that I can try my personal gf function first else fallback to the vim-rails ones

**Comment by jiz4oh** [comment]
especial I want it's works with [vim-gf-user](https://github.com/kana/vim-gf-user/blob/master/doc/gf-user.txt)

**Comment by tpope** [comment]
If you're looking to customize the map, then the last thing you want is `s:map_gf`, as all it does is define its own `gf` map. Instead, follow what the map points at: `<Plug><cfile>`. It in turn is defined to point at `rails#ruby_cfile()` or `rails#sprockets_cfile()`, depending on the file type.

**Comment by jiz4oh** [comment]
thanks your patiently explain, I have finished my plugin by `rails#ruby_cfile()` and `rails#sprockets_cfile()`
